### ISSUE TITLE
Verify that appended entries are not modified

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#11167]
I was wondering though, how could we guarantee that someone wouldn't change it without meaning to in the future? How to enforce that it returns a new, immutable value in the future? I don't have any great idea, tbh. I have some ideas - a parameterized unit test, for each possible value types, which sends at least 3 commands (buffering the commands in memory instead of passing them to the dispatcher), and verifying that they are exactly what we expect and haven't been touched - but none of them are foolproof, so I'm not going to insist here.

It might be interesting to look into annotation checkers around immutability in the future, though.

_Originally posted by @npepinpe in https://github.com/camunda/zeebe/pull/11132#pullrequestreview-1202274288_

**Comment by megglos** [comment]
Gain and how seems unclear, moving to backlog now, @npepinpe do you have any input on this?

**Comment by npepinpe** [comment]
The complete write pipeline depends on whatever we pass being immutable. There is no real guarantee at the moment other than us being very careful. This can break subtly, and if we do, we could be writing different bytes than expected or garbage. This would likely only be caught during processing. 

Take the `CommandApiRequestHandler` for example. We read the request's value into a `UnifiedRecordValue` object. Before the dispatcher replacement, we were actually always reusing the `UnifiedRecordValue` instance on every request (for the same value type, of course), since we were immediately serializing it anyway and copying it to a different buffer. But now we pass it along all the way down to the Raft pipeline as is. If we were to reuse it, it would likely break many things, and at worst in very subtle ways.

Best case scenario this causes an error where we essentially skip the record and write an error one instead (i.e. our usual error handling). Worst case scenario, the data is "read-able" but wrong, and we actual do some processing with it.

P.S. Posting this on a Sunday not because I'm working, but because I saw I had the comment written and hadn't clicked on comment :smile:

**Comment by npepinpe** [comment]
Closing, I don't expect we will work on this anytime soon.
