### ISSUE TITLE
Store commit index in raft MetaStore

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#13790]
Currently, on restart a partition's commitIndex is initialized to 0. This is perfectly fine, as we can reliably re-built the latest commitIndex from the quorum. 

In practice though, there can be disaster scenarios where data loss occur in one or more replica. In this cases there are chances that the replicas with data loss forms a quorum and overwrites data in the replica that actually has the correct latest data. We cannot 100% prevent data corruption or loss in case quorum of nodes lose their data. But we might be able to detect or prevent some inconsistencies.

The goal is to persist commitIndex in MetaStore. On restart a replica initialize commitIndex from the MetaStore. If the replicas with data loss forms a quorum, then the node with the latest committed data can detect this when it tries to overwrite its entries by the entries received from the new leader. This will still require manual intervention to recover, and might still result in some data loss. However, it is better than the current scenario, where we silently overwrite correct data.

Caveats: Writing commitIndex to MetaStore can add more I/O. Delayed and less frequent flushing would be acceptable in this case.

**Comment by megglos** [comment]
ZDP-Triage:
- it will help to detect corruption states before potentially loosing data
- might be a low-hanging fruit
- was relevant in an incident for a self-managed customer in May

**Comment by megglos** [comment]
ZDP-Planning:
- we don't consider it urgent, no reassingment

**Comment by npepinpe** [comment]
So, writing the commit index to the meta store will likely incur some I/O penalty, as we would be flushing every time.

In the issue description, we write:

> Delayed and less frequent flushing would be acceptable in this case.

So the idea would be to delay flushing here? Meaning, we're OK with the information stored in this file to be slightly outdated?

I would propose then that we write the file without explicitly flushing. Since we anyway flush the meta store after a standard flush, there wouldn't be too much gap.

**Comment by npepinpe** [comment]
One little hiccup. So, let's say I have three nodes, and commit 100 entries at term 1. Then all nodes shut down, and two nodes suffer data loss. Then they commit 50 entries at term 1. The third node comes back with its old data. Right now, nothing is detected amiss since the index and terms match, so the node with old data simply "assumes" that it already has the entries, and returns an OK to the leader. This is because we don't truncate unless the terms differ.

However, this is inconsistent here.
