### ISSUE TITLE
Benchmark with large state drops in performance rather quickly

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#13977]
**Describe the bug**

I have set up a benchmark with [default settings](https://github.com/zeebe-io/benchmark-helm/blob/main/charts/zeebe-benchmark/values.yaml) and three starters instead of one. This means we are creating three times the load, that we can handle. 450 Process instances are created and ~150 are completed. 

I wanted to verify, that we can handle normal processing (creation and completion) even if the accumulate more state, and that we are not failing. 

This experiment showed that this is right now not the case.

We can see that rather soon the processing slows down rapidly, and at some point, it completely died because of full disks.

![general](https://github.com/camunda/zeebe/assets/2758593/4c605eb1-103d-4c5c-b3d0-55c48d1eb868)

Taking a look at the snapshot metrics we can see that the problems already occur on smaller snapshot size, we expected to better handle such with introducing SST-Partition in #12033. 

![snapshot](https://github.com/camunda/zeebe/assets/2758593/67b1e866-bd45-4c60-8500-87ed242bc8c9)

The latency goes really high, which explains the low throughput.

![latency](https://github.com/camunda/zeebe/assets/2758593/43b7cc6d-91fb-4260-b8a7-1d33bfde59bc)

Mostly interesting is the commit latency which seems to spike.

![commit-latency](https://github.com/camunda/zeebe/assets/2758593/066cad30-c563-48a5-b10d-258f0de13444)

In the raft metrics we can also see that the replication rate goes down, and snapshot replication takes a while.

![raft](https://github.com/camunda/zeebe/assets/2758593/10783e71-2494-486b-bd40-a6dba73e66c7)

After discussing with @npepinpe we thought it might be related to RocksDb checkpointing behavior and flushing all mem-tables to disk, when WAL is disabled. We need to investigate this further.

Furthermore, we have seen in the IO metrics that the read metrics spiking quite high. This might also explain that our commit latency is fluctuating since our disk is throttled, another thing to investigate

![io-metrics](https://github.com/camunda/zeebe/assets/2758593/c6d4978c-a3cc-4450-9896-3c0a038ee223)

**To Reproduce**

Run a benchmark with more load than it can complete.

**Expected behavior**

Not a failing system, degraded performance due to backpressure but stable processing throughput and latency.

**Comment by npepinpe** [comment]
> I wanted to verify, that we can handle normal processing (creation and completion) even if the accumulate more state, and that we are not failing.

I think the benchmark is a bit misleading then. With job polling, we prioritize older jobs for activation, so as we create more processes, they are "waiting" for the older ones to finish, which would explain why the latency keeps going up regardless. Does that make sense? To test instead, we should build a large state, and then start PIs with different job types.

**Comment by Zelldon** [comment]
# 🕵🏼 Investigation of disk throttling

As written above after discussing with @npepinpe we assumed that the issue appears to disk throttling, which I wanted to investigate further.

Since the leadership in the cluster is well distributed I just picked on disk to verify the throttling. 

![pvc](https://github.com/camunda/zeebe/assets/2758593/6e61ba05-dd43-455d-bdf0-4770af894e40)


First I tried the metrics explorer to find the throttling metrics, similar to what I used in the past [here ](https://github.com/camunda/zeebe/issues/8551#issuecomment-1009976822). Turns out that these metrics have been removed. This means there is no longer the way to easily say whether it is throttled or not.

But still I was able to see how much read and write ops and bytes are observed.
![disk-write-read-bytes](https://github.com/camunda/zeebe/assets/2758593/5d3c874d-3ccf-48a7-a077-3bfb6aa8e9f2)
![disk-write-read-ops](https://github.com/camunda/zeebe/assets/2758593/dead182b-6412-4904-bcbf-b85768d03f55)


Later I found out that we can also check the VM details in the disk section

![pvc-instance-mapping](https://github.com/camunda/zeebe/assets/2758593/fdb0f468-a8ba-4b38-8d08-583e5eede8f0)


![vm-details](https://github.com/camunda/zeebe/assets/2758593/a8618538-3863-4e72-8b9a-9553f8388c40)

We can see all related metrics to that VM (and disk attached to). Interesting is that in these metrics we see that the read AND write are most of the time around 250 MB/s, which is actually the limit for that configuration, as we can see in the [docs](https://cloud.google.com/compute/docs/disks/performance#pd-ssd_8).

![n2-restrictions](https://github.com/camunda/zeebe/assets/2758593/d51ae511-cf19-407b-9101-c9bb4b5ea832)

**Comment by Zelldon** [comment]
> > I wanted to verify, that we can handle normal processing (creation and completion) even if the accumulate more state, and that we are not failing.
> 
> I think the benchmark is a bit misleading then. With job polling, we prioritize older jobs for activation, so as we create more processes, they are "waiting" for the older ones to finish, which would explain why the latency keeps going up regardless. Does that make sense? To test instead, we should build a large state, and then start PIs with different job types.

Not sure whether I agree, since this is the normal use case our users would also run

**Comment by npepinpe** [comment]
That's fair, though I don't know what's the normal use case tbh :smile: If you have many different processes, some long running, some not, then the long running may end up taking more of the state, and the short ones would still be responsive (or that's what I expect :crossed_fingers: )

**Comment by Zelldon** [comment]
# Further benchmarking 🧪 
I have set up a new benchmark to just verify whether we are "just" throttled. 

I increased the disk size and CPU count.

```
--- a/charts/zeebe-benchmark/values.yaml
+++ b/charts/zeebe-benchmark/values.yaml
@@ -50,7 +50,7 @@ worker:
 # Starter configuration for the to be deployed starter application
 starter:
   # Starter.replicas defines how many replicas of the application should be deployed
-  replicas: 1
+  replicas: 3
   # Starter.rate defines with which rate process instances should be created by the starter
   rate: 150
 
@@ -207,23 +207,25 @@ camunda-platform:
             name: zeebe-config
             key: java-opts
             optional: true
-
+    # Ignore the stable VM node taints
+    tolerations:
+      - key: cloud.google.com/gke-spot
+        operator: Equal
+        effect: NoSchedule
+        value: 'false'
     # Resources configuration to set request and limit configuration for the container https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limitsS
     resources:
       limits:
-        cpu: 1350m
+        cpu: 8
         memory: 4Gi
       requests:
-        cpu: 1350m
+        cpu: 8
         memory: 2Gi
 
-    nodeSelector:
-      cloud.google.com/gke-nodepool: n2-standard-2
-
     # PvcAccessModes can be used to configure the persistent volume claim access mode https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
     pvcAccessMode: [ "ReadWriteOnce" ]
     # PvcSize defines the persistent volume claim size, which is used by each broker pod https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
-    pvcSize: 32Gi
+    pvcSize: 128Gi
```

Looks like with just more CPU's and disk size we can do around ~370 process instance create and complete per second 🤯 With the same amount of partitions.

![general](https://github.com/camunda/zeebe/assets/2758593/e4e75703-c575-44b8-aa43-07c03c87a2a7)

Note: that I haven't changed anything else, the thread count is the same. I think it is just not write/read throttled so much anymore 😅

**Comment by Zelldon** [comment]
I tried to reproduce this behavior with our new JMH tests. I adjusted the `LargeStateControllerPerformanceTest` 

```diff

--- a/broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/perf/LargeStateControllerPerformanceTest.java
+++ b/broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/perf/LargeStateControllerPerformanceTest.java
@@ -10,6 +10,8 @@ package io.camunda.zeebe.broker.system.partitions.impl.perf;
 import static org.assertj.core.api.Assertions.assertThat;
 
 import io.camunda.zeebe.broker.system.partitions.impl.StateControllerImpl;
+import io.camunda.zeebe.snapshots.PersistedSnapshot;
+import io.camunda.zeebe.snapshots.TransientSnapshot;
 import io.camunda.zeebe.test.util.jmh.JMHTestCase;
 import io.camunda.zeebe.test.util.junit.JMHTest;
 import java.util.Map;
@@ -42,20 +44,43 @@ public class LargeStateControllerPerformanceTest {
   private static final double ONE_GB = Math.pow(2.0, 30.0);
   private static final double SIZE_GB =
       Double.parseDouble(
-          System.getenv().getOrDefault("LARGE_STATE_CONTROLLER_PERFORMANCE_TEST_SIZE_GB", "0.5"));
+          System.getenv().getOrDefault("LARGE_STATE_CONTROLLER_PERFORMANCE_TEST_SIZE_GB", "4.0"));
   private static final Map<Double, Double> KNOWN_REFERENCE_SCORES = Map.of(0.5, 10.0, 4.0, 9.0);
 
   private TestState.TestContext context;
+  private TransientSnapshot snapshot;
 
   @Setup
   public void setup() throws Throwable {
     final var sizeInBytes = Math.round(SIZE_GB * ONE_GB);
 
     LOG.info("Creating a test state of approximately {}GB; please hold the line...", SIZE_GB);
-    context = new TestState().generateContext(sizeInBytes);
+    context = new TestState().generateContextWithoutSnapshot(sizeInBytes);
     LOG.info(
         "Created a test size with a total size of {}GB",
         String.format("%.3f", context.snapshotSize() / ONE_GB));
+
+    final var controller =
+        new StateControllerImpl(
+            context.dbFactory(),
+            context.snapshotStore(),
+            context.temporaryFolder().resolve("runtime"),
+            ignored -> Optional.empty(),
+            ignored -> 0L,
+            context.snapshotStoreFactory().getSnapshotStoreConcurrencyControl(1));
+
+    // when
+    //noinspection EmptyTryBlock
+
+    snapshot = context.snapshotStore().newTransientSnapshot(1, 1, 1, 1).get();
+
+    snapshot.take(
+        p -> {
+          context
+              .dbFactory()
+              .createDb(context.temporaryFolder().resolve("runtime").toFile())
+              .createSnapshot(p.toFile());
+        });
   }
 
   @TearDown
@@ -79,20 +104,8 @@ public class LargeStateControllerPerformanceTest {
   }
 
   @Benchmark
-  public void measureStateRecovery() throws Exception {
+  public PersistedSnapshot measureStateRecovery() {
     // given
-    //noinspection deprecation
-    final var controller =
-        new StateControllerImpl(
-            context.dbFactory(),
-            context.snapshotStore(),
-            context.temporaryFolder().resolve("runtime"),
-            ignored -> Optional.empty(),
-            ignored -> 0L,
-            context.snapshotStoreFactory().getSnapshotStoreConcurrencyControl(1));
-
-    // when
-    //noinspection EmptyTryBlock
-    try (final var ignored = controller.recover().join()) {}
+    return snapshot.persist().join();
   }
 }
diff --git a/broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/perf/TestState.java b/broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/perf/TestState.java
index 3bf0de9eda..a3ed72d295 100644
--- a/broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/perf/TestState.java
+++ b/broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/perf/TestState.java
@@ -50,6 +50,23 @@ final class TestState {
         actorScheduler, tempDirectory, snapshotStore, createDbFactory(), storeFactory);
   }
 
+  TestContext generateContextWithoutSnapshot(final long sizeInBytes) throws Exception {
+    final var tempDirectory = Files.createTempDirectory("statePerf");
+    final var actorScheduler =
+        ActorScheduler.newActorScheduler()
+            .setIoBoundActorThreadCount(1)
+            .setCpuBoundActorThreadCount(1)
+            .build();
+    actorScheduler.start();
+
+    final var storeFactory = new FileBasedSnapshotStoreFactory(actorScheduler, 1);
+    final var snapshotStore = createSnapshotStore(storeFactory, tempDirectory);
+    generateSnapshot(tempDirectory, sizeInBytes);
+
+    return new TestContext(
+        actorScheduler, tempDirectory, snapshotStore, createDbFactory(), storeFactory);
+  }
+
   private void generateSnapshot(
       final ConstructableSnapshotStore snapshotStore, final long sizeInBytes) {
     final var snapshot = snapshotStore.newTransientSnapshot(1, 1, 1, 1).get();
```

I have run it with a smaller state and a larger state but the results where the same.

```
perf.LargeStateControllerPerformanceTest - Created a test size with a total size of 0.607GB
LargeStateControllerPerformanceTest.measureStateRecovery  thrpt   25  210967.320 ± 7832.889  ops/s
.system.partitions.impl.perf.LargeStateControllerPerformanceTest - Created a test size with a total size of 4.089GB
LargeStateControllerPerformanceTest.measureStateRecovery  thrpt   25  212625.791 ± 1720.160  ops/s
```

 I think the reason here is that the buffers/caches etc are not full/dirty when doing the checkpoint/snapshot multiple times (as you mentioned @npepinpe ) Not sure how to better test this, but I think from the benchmark we can see that there is something going on related to snapshots on bigger state. But I have no clear answer it. Maybe we find or handle it when we handle the other topic of improving snapshot replication. I would defer this issue for now until we have completed the other EPIC.

**Comment by Zelldon** [comment]
Discussed with @npepinpe 

we realized that it might be related to snapshot checksum creation after snapshot is committed, since we have to read the complete snapshot.

We might have an idea to fix this via read-only opening the db and not doing the checksums by hand.

We will look into this next, and do the other afterwards.

**Comment by megglos** [comment]
ZDP-Triage:
- will be handled as part of the https://github.com/camunda/product-hub/issues/1480 epic

**Comment by Zelldon** [comment]
Since our suspicion was that checksumming is the issue [I removed the checksum stuff and run another benchmark](https://github.com/camunda/zeebe/tree/ck-snapshot-checksum). 

![snapshot-duration](https://github.com/camunda/zeebe/assets/2758593/e7baec11-a4ef-466a-b422-270462ab6f83)

[It is still slow, and we can see that even now snapshotting duration goes up.](https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&refresh=10s&var-DS_PROMETHEUS=Prometheus&var-cluster=All&var-namespace=ck-no-checksums&var-pod=All&var-partition=All&from=now-24h&to=now)




Interestingly is that the read metrics are now look bit better in grafana (?). But in gcp we can see that it is still running on the limits.

![read-gcp](https://github.com/camunda/zeebe/assets/2758593/f9be0283-0ac0-45e1-b357-a9d90266edf9)
![read](https://github.com/camunda/zeebe/assets/2758593/6abea049-ac16-429f-ad7a-7f052c70e8f1)


Wondering whether I haven't removed all checksum stuff. Might need to check again. Or it is really related to checkpointing AND full memtables which need to be flushed etc.

I will start another one with WAL enabled.

\cc @npepinpe

**Comment by npepinpe** [comment]
FYI, I did make it work, with two caveats:

1. RocksDB uses CRC32C, not CRC32, so that was already one reason why I'd never get the same things :smile: 
2. If WAL is enabled, the checksums you get are partial. **I don't know how to make this work with WAL enabled yet**.

Here's what I would propose:

Open a PR upstream to enable usage of the full file checksum feature, delegating checksum computation to RocksDB. This will allow us to then get the SST file info (path, size, and checksum) directly from the manifest, which will greatly speed integrity checking.

While we wait for the PR to be merged AND released (which could take a while), we can implement the following temporary solution (which will still minimize refactoring once the upstream PR is released):

Use the `EventListener` concept from RocksDB, and listen for two events: `OnTableFileCreated` and `OnTableFileDeleted`. These refer to whenever a SST file is created (written) and deleted. Since SST files are immutable, we can asynchronously compute the checksum for that file at that point. This effectively spreads out computing the checksum into small chunks, instead of one big blocking task. Save the results in memory - whenever a file is created, compute its checksum, and whenever it's deleted, remove it from the in-memory table.

When a snapshot is created, we do the following:

- Create a new checkpoint at the snapshot directory location.
- Create a new `SfvChecksum` instance.
- Iterate over all files in the checkpoint directory.
- If it's an SST file and it's in the in-memory SST file table, update the `SfvChecksum` with the file name and pre-computed checksum.
- Otherwise, update the `SfvChecksum` with the file's contents.
- Serialize the `SfvChecksum` instance to a file inside the snapshot directory.

Couple things here: 

- We need to possible compute the checksum for some SST files that were creating during the checkpointing operation, and since the listeners are asynchronous, may not be in the in-memory table.
- We'll have to drop the idea of a "combined" checksum, which means for verification of the snapshot integrity during replication, we'll need to do it file by file (or "chunk" by "chunk"). It is possible to combine multiple CRC32 checksums, but since our combined checksum includes the file name, it's not possible for us without re-reading all the files.
- We're potentially computing the checksum of some files for no reason.

Before implementing everything, we should benchmark that taking a snapshot on large state is indeed much faster like this, and that the impact of computing the checksum as files are created is minimal.

The goal in the end would be that we do most of the refactoring required for the long term solution (i.e. the use of full file checksum in RocksDB), but we have a temporary patch where we manually compute the checksum as the SST files are created which we will later replace with the full file checksum, so all this will still bring us closer to our desired final result.

Some open questions:

- Now that `zb-db` is generating the checksum file itself, should verification of the snapshot also move to that module? Probably, otherwise we have a strong coupling of the `snapshot` module and `zb-db`.

**Comment by npepinpe** [comment]
BTW I just edited the comment while apparently you were reading it ;)

**Comment by npepinpe** [comment]
Thanks to @Zelldon , we have a better solution: we can reuse the functionality of RocksDB to create options from string properties. So we'll enable the full file checksum feature using the property `file_checksum_gen_factory = FileChecksumGenCrc32cFactory`, which will cause RocksDB to write out full file checksum whenever a new SST file is written. We've already tested that this works well, **as long as WAL is disabled**.

Next step is figuring out how to read the checksum list from the MANIFEST. We'll open two PRs on upstream:

1. Pass the full file checksum to the `RocksDB#getLiveFilesMetadata`, which is a very easy/straight-forward PR, hopefully no push back from their side.
2. Allow setting a checksum generator factory via the Java API. This one might be more complex/need more discussion on the option format from their side, hence why we want to do it in 2 PRs (since we have a workaround already for this second PR).

Since we don't know how long it takes to release a PR, we still need a temporary solution. We'll research this week (time boxed) how to read the checksum list back from the manifest ourselves without waiting for the PR.

**Comment by npepinpe** [comment]
We can possibly use FFI to get the checksums by using the [RocksDB C API](https://github.com/facebook/rocksdb/blob/ba597514309b686d8addb59616f067d5522186b7/include/rocksdb/c.h)

**Comment by npepinpe** [comment]
It's unlikely we can use the C API of RocksDB because they simply stuff their C++ structs in there, so trying to access any of their members via FFI will be problematic primarily due to lack of knowledge of C++ classes and function name mangling.

Anyway, in the meantime we've opened two PRs upstream for this feature:

- https://github.com/facebook/rocksdb/pull/11770
- https://github.com/facebook/rocksdb/pull/11772

:crossed_fingers: they get merged and released quick-ish

**Comment by npepinpe** [comment]
So the next step is preparing our code to use those APIs, but providing temporary implementations of them. These temporary implementations could be:

1. Reading the manifest file and parsing the deleted file/new file records to fetch the live checksums (high complexity, reverse engineer the C++ code, brittle to some extent)
2. Using the listener approach and computing the checksums ourselves to spread the impact over time in small chunks (adds some complexity, but simplest approach)
3. Magically figuring out how to use the C API and the C++ structs from FFI (no idea how)
4. Using [javacpp](https://github.com/bytedeco/javacpp) to generate, compile, and build a small extension for these APIs (high complexity)
5. Use our own release of RocksDB from a fork

Nothing is really interesting, but we can still make progress on the required refactoring anyway.

**Comment by npepinpe** [comment]
A 7th option, as proposed by @Zelldon: let's pause this here, and move on to the snapshot replication. Hopefully by the time we're done there, our upstream PRs will be merged :+1:

**Comment by npepinpe** [comment]
I had to increase the snapshot request timeout to 15s, I also had to apply the OOM fix (which is now merged), increase the broker memory to 5.3Gi (the max on the nodes), and increase disk size to 256Gi (large snapshot and all).

Here's the script I used to "quickly" generate large state. It can generate ~1GB in 2-3 minutes.

```bash
#!/bin/bash

PORT=${1:-26500}
JOBS=${2:-5}
let i=0

while :; do
  for j in `seq 1 "$JOBS"`; do
    let i++
    echo "{\"$(tr -dc A-Za-z </dev/urandom | head -c $(( $RANDOM % 50 + 3 )))\": \"$(tr -dc A-Za-z0-9 </dev/urandom | head -c 3145728)\"}" > /tmp/generate-${PORT}-${j}
    ~/bin/zbctl --insecure --requestTimeout 15s --address "localhost:${PORT}" publish message foo --ttl 720h --correlationKey "$i" --variables /tmp/generate-${PORT}-${j} &
  done

  # wait for all jobs to finish
  wait $(jobs -p)
done
```

This publishes messages with a large payload (3MB), randomly generated (so RocksDB cannot do compression too much on the SST files), with TTL of 1 week. Doing this you avoid the processing slow down associated with creating many long living instances.

**Comment by npepinpe** [comment]
This shows replication is roughly ~30-45s per GB of state (I know, that's a pretty big variance :smile:). I assume the number of files is also a factor, since we replicate them one at a time.

The biggest blocker was the snapshot replication loop, which makes a 3-4 minutes replication into a 30 minutes (or more) startup - an increase of 10x. So I would propose fixing snapshot replication issues first before optimizing speed.

**Comment by Zelldon** [comment]
I can already see how we can add this to zbchaos 🤩 and automate a chaos experiment with this.

**Comment by npepinpe** [comment]
> I can already see how we can add this to zbchaos 🤩 and automate a chaos experiment with this.

We could speed things up by increasing the max message size across the board and sending bigger payloads maybe. I'm not sure by how much - I imagine bigger payloads might take longer to persist, so who knows...

**Comment by Zelldon** [comment]
Removing my assignment as I don't think I will work on this soon.

**Comment by npepinpe** [comment]
I'm closing this, as we did major improvements, and we've extracted epics out of this. It's not fully solved, but I think we can work with the other issues.
