### ISSUE TITLE
Timers of banned instances are forever re-triggered

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#14213]
**Describe the bug**

During [the game day](https://confluence.camunda.com/display/ZEEBE/2023-09-07+Game+Day), we had a case of a loop around a timer catch event which ended up producing an enormous amount of records. To recover, we thought we could just ban the instances. Turns out, even when banned, the timers kept re-triggering, and the system was writing timer trigger commands over and over, since it's not aware of banned instances.

> **Note**
> We were also confused by the ban metrics, since banning the same process instance twice will increment the counter twice, even if really, only one instance was banned.

**To Reproduce**

Deploy this beautiful looping process:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:zeebe="http://camunda.org/schema/zeebe/1.0" xmlns:modeler="http://camunda.org/schema/modeler/1.0" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" id="Definitions_1" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Web Modeler" exporterVersion="54e0234" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.2.0" camunda:diagramRelationId="eb53fcb1-5305-43cf-8c22-9b5c514460cf">
  <bpmn:process id="GamedayProcess" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1" name="Send Email newsletter">
      <bpmn:outgoing>Flow_0yg4sg4</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:sequenceFlow id="Flow_0yg4sg4" sourceRef="StartEvent_1" targetRef="Event_02vb3b2" />
    <bpmn:intermediateCatchEvent id="Event_02vb3b2" name="16 o&#39;clock">
      <bpmn:incoming>Flow_0yg4sg4</bpmn:incoming>
      <bpmn:incoming>Flow_0ucihdu</bpmn:incoming>
      <bpmn:incoming>Flow_1dr09o3</bpmn:incoming>
      <bpmn:outgoing>Flow_0ucihdu</bpmn:outgoing>
      <bpmn:outgoing>Flow_0bbnbt4</bpmn:outgoing>
      <bpmn:timerEventDefinition id="TimerEventDefinition_1mcgxr7">
        <bpmn:timeDuration xsi:type="bpmn:tFormalExpression">=date and time(today(), time("09:00:00@Europe/Berlin")) - now()</bpmn:timeDuration>
      </bpmn:timerEventDefinition>
    </bpmn:intermediateCatchEvent>
    <bpmn:sequenceFlow id="Flow_1537k1v" sourceRef="Gateway_1knikyw" targetRef="Activity_1r2d7uw" />
    <bpmn:endEvent id="Event_1rb64gr">
      <bpmn:incoming>Flow_1jfq4dj</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:parallelGateway id="Gateway_1knikyw">
      <bpmn:incoming>Flow_0bbnbt4</bpmn:incoming>
      <bpmn:outgoing>Flow_1dr09o3</bpmn:outgoing>
      <bpmn:outgoing>Flow_1537k1v</bpmn:outgoing>
    </bpmn:parallelGateway>
    <bpmn:sequenceFlow id="Flow_1jfq4dj" sourceRef="Activity_1r2d7uw" targetRef="Event_1rb64gr" />
    <bpmn:serviceTask id="Activity_1r2d7uw" name="Send Email">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="sendNewsletter" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_1537k1v</bpmn:incoming>
      <bpmn:outgoing>Flow_1jfq4dj</bpmn:outgoing>
    </bpmn:serviceTask>
    <bpmn:sequenceFlow id="Flow_0ucihdu" sourceRef="Event_02vb3b2" targetRef="Event_02vb3b2" />
    <bpmn:sequenceFlow id="Flow_1dr09o3" name="Next Day again" sourceRef="Gateway_1knikyw" targetRef="Event_02vb3b2" />
    <bpmn:sequenceFlow id="Flow_0bbnbt4" sourceRef="Event_02vb3b2" targetRef="Gateway_1knikyw" />
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="GamedayProcess">
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="152" y="120" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="141" y="166" width="57" height="27" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_121xx9h_di" bpmnElement="Event_02vb3b2">
        <dc:Bounds x="252" y="120" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="255" y="93" width="50" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1rb64gr_di" bpmnElement="Event_1rb64gr">
        <dc:Bounds x="572" y="120" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Gateway_0i1s8cx_di" bpmnElement="Gateway_1knikyw">
        <dc:Bounds x="335" y="113" width="50" height="50" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_16cmsco_di" bpmnElement="Activity_1r2d7uw">
        <dc:Bounds x="420" y="98" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_0yg4sg4_di" bpmnElement="Flow_0yg4sg4">
        <di:waypoint x="188" y="138" />
        <di:waypoint x="252" y="138" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1537k1v_di" bpmnElement="Flow_1537k1v">
        <di:waypoint x="385" y="138" />
        <di:waypoint x="420" y="138" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1jfq4dj_di" bpmnElement="Flow_1jfq4dj">
        <di:waypoint x="520" y="138" />
        <di:waypoint x="572" y="138" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0ucihdu_di" bpmnElement="Flow_0ucihdu">
        <di:waypoint x="252" y="138" />
        <di:waypoint x="252" y="138" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1dr09o3_di" bpmnElement="Flow_1dr09o3">
        <di:waypoint x="360" y="163" />
        <di:waypoint x="360" y="210" />
        <di:waypoint x="270" y="210" />
        <di:waypoint x="270" y="156" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="277" y="192" width="76" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0bbnbt4_di" bpmnElement="Flow_0bbnbt4">
        <di:waypoint x="288" y="138" />
        <di:waypoint x="335" y="138" />
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```

Run it, wait for it to build some state, then ban it. The system will keep writing timer trigger commands. So our force ban feature works, but it doesn't allow us to recover from all cases.

I suspect more process-instance-adjacent commands (timers, jobs, etc.) may have other issues as well.

**Expected behavior**

Banning instance stops any activity related to that instance.

-------

https://jira.camunda.com/browse/SUPPORT-23524

**Comment by npepinpe** [comment]
Severity is high because there is no way to recover right now, you must :fire: the cluster.

**Comment by abbasadel** [comment]
ZPA triage: 
- We think this affects all the current versions and probably the next one.
- Impact is severe and you need to burn the cluster
- We think the correct behavoir is that timers can not be triggered on banned instances
- When working on this, we need to check if this is affecting other commands and open new issues for them (limit the scope of this bug)
- We think this is important to work on, so we make it 'upcoming'  and size it as `Medium`

**Comment by korthout** [comment]
You're on the right path @berkaycanbc.

>Turns out, even when banned, the timers kept re-triggering, and the system was writing timer trigger commands over and over

The description discusses the timer trigger command, but the test above asserts the timer triggered events. The command is correctly skipped from being processed because of the `Engine` lines 126-128 you shared. So, we don't process these commands. But this issue is about the engine writing commands about the banned instance. We should stop any activity for banned instances. 

Can you try changing your assertion to `.withIntent(TimerIntent.TRIGGER)`?

---

```java
    final var bannedInstanceState =
        (MutableBannedInstanceState) ENGINE.getProcessingState().getBannedInstanceState();
    bannedInstanceState.banProcessInstance(processInstanceKey);
```

Here, you're correctly banning the instance. The engine cannot make any state changes without reflecting these on the log stream with some event. For banned instances, this is reflected by `Error` events. Sadly, our engine test infrastructure cannot ban an instance in the same way a user can via the admin service.

🔧 I suggest you add this capability to the EngineRule and use it in your test. This should also show better what is happening when you inspect the printed compacted log. For example, whether or not any Timer records are written to the log after the process instance is banned. You can look at how this is implemented in the broker's admin service:
https://github.com/camunda/zeebe/blob/2ad42a8032ba36e25bb96173f7bdd9946b6258d4/zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartitionAdminAccess.java#L195

---

Lastly, I noticed a strange sequence flow that is outgoing from the timer and immediately back to the timer. This results in an additional token (the intermediate timer catch event implicitly functions as a forking parallel gateway). You should remove this to make it easier. Additionally, I recommend using the BPMN model API to create the process rather than an XML file, making the test easier to understand.

```xml
<bpmn:sequenceFlow id="Flow_0ucihdu" sourceRef="Event_02vb3b2" targetRef="Event_02vb3b2" />
```

**Comment by berkaycanbc** [comment]
## Further findings

### The issue can even be produced without having a loop in the BPMN model

```java
@Test
  public void shouldNotTriggerTimerEventWhenInstanceIsBanned() {
    // given
    final var processId = "process1";
    ENGINE
        .deployment()
        .withXmlResource(
            Bpmn.createExecutableProcess(processId)
                .startEvent("start")
                .intermediateCatchEvent("timer", b -> b.timerWithDuration("PT3S"))
                .endEvent("end")
                .done())
        .deploy();

    final long processInstanceKey = ENGINE.processInstance().ofBpmnProcessId(processId).create();

    assertThat(
            RecordingExporter.timerRecords()
                .withIntents(TimerIntent.CREATED)
                .withProcessInstanceKey(processInstanceKey)
                .getFirst())
        .isNotNull();

    // when
    ENGINE.processInstance().withInstanceKey(processInstanceKey).banProcessInstance();
    final var bannedInstanceState =
        (MutableBannedInstanceState) ENGINE.getProcessingState().getBannedInstanceState();
    bannedInstanceState.banProcessInstance(processInstanceKey);

    // then
    assertThat(
            RecordingExporter.timerRecords()
                .withIntents(TimerIntent.TRIGGER)
                .withProcessInstanceKey(processInstanceKey)
                .exists())
        .isFalse();
  }
```

The above test case fails because we still write timer `TRIGGER` event to the state as follows:
```
15:16:33 C DPLY  CREATE         - #01-> -1  -1 - 
15:16:33 E PROC  CREATED        - #02->#01 K01 - process.xml -> "process1" (version:1)
15:16:33 E DPLY  CREATED        - #03->#01 K02 - process.xml
15:16:33 C CREA  CREATE         - #04-> -1  -1 - new <process "process1"> (default start)  (no vars)
15:16:33 C PI    ACTIVATE       - #05->#04 K03 - PROCESS "process1" in <process "process1"[K03]>
15:16:33 E CREA  CREATED        - #06->#04 K04 - new <process "process1"> (default start)  (no vars)
15:16:33 E PI    ACTIVATING     - #07->#04 K03 - PROCESS "process1" in <process "process1"[K03]>
15:16:33 E PI    ACTIVATED      - #08->#04 K03 - PROCESS "process1" in <process "process1"[K03]>
15:16:33 C PI    ACTIVATE       - #09->#04  -1 - START_EVENT "start" in <process "process1"[K03]>
15:16:33 E PI    ACTIVATING     - #10->#04 K05 - START_EVENT "start" in <process "process1"[K03]>
15:16:33 E PI    ACTIVATED      - #11->#04 K05 - START_EVENT "start" in <process "process1"[K03]>
15:16:33 C PI    COMPLETE       - #12->#04 K05 - START_EVENT "start" in <process "process1"[K03]>
15:16:33 E PI    COMPLETING     - #13->#04 K05 - START_EVENT "start" in <process "process1"[K03]>
15:16:33 E PI    COMPLETED      - #14->#04 K05 - START_EVENT "start" in <process "process1"[K03]>
15:16:33 E PI    SEQ_FLOW_TAKEN - #15->#04 K06 - SEQUENCE_FLOW "sequenc..f5158e4" in <process "process1"[K03]>
15:16:33 C PI    ACTIVATE       - #16->#04 K07 - INTERMEDIATE_CATCH_EVENT "timer" in <process "process1"[K03]>
15:16:33 E PI    ACTIVATING     - #17->#04 K07 - INTERMEDIATE_CATCH_EVENT "timer" in <process "process1"[K03]>
15:16:33 E TIME  CREATED        - #18->#04 K08 -  @"timer"[K07]  in <process "K01"[K03]> due T15:16:36.361
15:16:33 E PI    ACTIVATED      - #19->#04 K07 - INTERMEDIATE_CATCH_EVENT "timer" in <process "process1"[K03]>
15:16:33 E ERROR CREATED        - #20-> -1 K03 - "Instance was banned from outside."  in <process ?[K03]> (java.lang.Exception: Instance was banned from outside.
	at io.camunda.zeebe.engine.util.client.Pro..)
15:16:36 C TIME  TRIGGER        - #21-> -1 K08 -  @"timer"[K07]  in <process "K01"[K03]> due T15:16:36.361
```

As seen above, the timer `TRIGGER` event is written to the log. For the next run of `DueDateTimerChecker`, it will again be written to the log.

### The same issue exists for other scheduled tasks
* `DueDateTimerChecker`: if timer is created and the related process instance is banned before triggering the timer, a timer record with `TimerIntent.TRIGGER` will forever be written to the log.
* `JobBackoffChecker`: if job is failed with a `retryBackoff > 0` and the related process instance is banned before re-activating the job, a job record with `JobIntent.RECUR_AFTER_BACKOFF` will forever be written to the log.
* `JobTimeoutChecker`: if a job is activated with a timeout and the related process instance is banned before the job is completed, a job record with `JobIntent.TIME_OUT` will forever be written to the log.
* `PendingProcessMessageSubscriptionChecker`: assuming process instance is created in partition 1; if message subscription is created in partition 2 and the related process instance is banned (in partition 2) before processing the `MessageSubscriptionIntent.CREATE` command, a ProcessMessageSubscription record with `MessageSubscriptionIntent.CREATE` will forever be sent to the partition 2.

The reason for these commands are forever written to the log is that they cannot be processed once the related process instance is banned:
When we ban the instance, the next process record is not passing the `isBanned` check here: https://github.com/camunda/zeebe/blob/42cc7744e88ad4aac655f115a8a270f0556e6432/zeebe/engine/src/main/java/io/camunda/zeebe/engine/Engine.java#L126-L128

Therefore, records cannot be updated in the state.

### Possible Solution

I am thinking to update timer, job and message subscription values in the state while banning the process instance. For example, removing the timer instance of banned process instance. Therefore, these records will not be available to the checkers.

To keep it simple, we can start with only updating timer values in the state.

@korthout WDYT? I would appreciate your comments on the findings I shared above as well.

**Comment by korthout** [comment]
Thanks @berkaycanbc for the investigation.

>We can update timer, job and message subscription values in the state while banning the process instance. For example, removing the timer instance of banned process instance. Therefore, these records will not be available to the checkers at all.

A banned instance is quarantined. This doesn't affect the rest of the system but still allows us to analyze it for the root cause of the associated bug. We should **not** remove its data as it removes our ability to analyze the instance.

>We can add a decorator to the checkers where it checks the banned instance state if the process instance of the related timer, job or message subscription is banned. If banned, we can update the state by writing events to remove timer, job or message subscription records from the state.

I like the decorator idea but not the data deletion part. We can use the knowledge of a banned instance to decide not to append the command.

This would mean we'd still encounter it when iterating over the expired timers each time, which could affect checker speed but at least it doesn't impact the logstream and stream processor. Another impact this has is that iterating over each expired timer also comes with a lookup of the banned instances column family, slowing down all checker activities.

This brings me to another proposal: moving the banned instance to quarantined versions of the column families.

As part of the Error record's event applying, we could delete the related data of the process instance and insert it in a special column family, for example by bitshifting the column family prefix value. However, this is a dangerous operation, as it:
- could fail
- is potentially hard to maintain (each new column family storing something about a process instance must be used)

So, I'm not sure this is the way to go. Let me know your own thoughts about all this.

**Comment by korthout** [comment]
It seems my thoughts have a wrong assumption: I believed that the timer trigger command for a single timer would only be written once to the log stream. My assumption was that the command cache would stop other encounters.

This appears not to be the case:
```
17:32:05 E ERROR     CREATED        - #43-> -1 K03 - "Instance was banned from outside."  in <process ?[K03]> (java.lang.Exception: Instance was banned from outside.
	at io.camunda.zeebe.engine.util.client.Pro..)
17:32:07 C TIME      TRIGGER        - #44-> -1 K16 -  @"Event_02vb3b2"[K13]  in <process "K01"[K03]> due T17:32:07.761
17:32:10 C TIME      TRIGGER        - #45-> -1 K16 -  @"Event_02vb3b2"[K13]  in <process "K01"[K03]> due T17:32:07.761
17:32:12 C TIME      TRIGGER        - #46-> -1 K16 -  @"Event_02vb3b2"[K13]  in <process "K01"[K03]> due T17:32:07.761
17:32:14 C TIME      TRIGGER        - #47-> -1 K16 -  @"Event_02vb3b2"[K13]  in <process "K01"[K03]> due T17:32:07.761
17:32:16 C TIME      TRIGGER        - #48-> -1 K16 -  @"Event_02vb3b2"[K13]  in <process "K01"[K03]> due T17:32:07.761
```

My suggestion to stop the biggest bleeding here: so let's fix the command cache.

**Comment by berkaycanbc** [comment]
After another round of investigation, the problem is clear now.

## Problem
After appending the `TimerIntent.TRIGGER` command to the log, we add the intent/key pair to the command cache. After processing the command and updating the state we remove the command from the cache. It is to prevent re-appending the same command to the log stream over and over without processing the previously appended command.

With a banned process instance here is what happens:

1)`DueDateTimerChecker` fetches timers from the state (including the timer of banned process instance) 
2) Checker appends `TimerIntent.TRIGGER` command to the log stream and puts it to the cache
3) Stream processor processes the command of the banned instance and removes it from the command cache
4) With next `DueDateTimerChecker` trigger, the checker fetches the timer of the banned process instance and step 2 above starts again

## Solution Idea
In the `Engine` https://github.com/camunda/camunda/blob/8f1eb2fc7925e4ffd88d078240042dde9cac8dda/zeebe/engine/src/main/java/io/camunda/zeebe/engine/Engine.java#L126-L130 we can mark `ProcessingResult` as skipped. Later in `ProcessingStateMachine` https://github.com/camunda/camunda/blob/8f1eb2fc7925e4ffd88d078240042dde9cac8dda/zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java#L666-L668 we can check if the result is skipped and do not remove it from the command cache.

Since the proposed solution also affects ZDP's domain I would like to ask opinion from @camunda/zeebe-distributed-platform team.

**Comment by korthout** [comment]
Another solution would be to check for banned instances in the `DueDateTimerChecker`. However, this would come at a potential performance cost: each timer requires an additional state look-up to see if it belongs to a banned instance.

Alternatively, we could move the data of a banned instance to a quarantined column family. This way, the `DueDateTimerChecker` would no longer encounter the timer. However, I believe this is too brittle and not easy to maintain.

So, I also favor this approach to avoid removing the entry from the cache. It's pragmatic.

**Comment by lenaschoenburg** [comment]
> we can check if the result is skipped and do not remove it from the command cache.

This solution is problematic when there are many banned instances:
1. The command cache fills up, rendering it ineffective for it's actual purpose.
2. The `DueDateTimerChecker` finds the same timers over and over again. If yielding is enabled, this could block the triggering of timers for non-banned instances.

**Comment by Zelldon** [comment]
I just wanted to add my 2 ct's (if allowed). 

I feel like we see here again the limitation of the banning of instances, where we should think about again to start to implement a different concept. 

When banning an instance we accumulate data, and by keeping things then also in the cache, we would even pollute now the caches (making them less efficient, and having a high resource usage, depending on how many instances are banned of course). Not sure whether this is a good approach. It could lead to OOMs, and on restart, the procedure will start new, as we don't remove the timers from the state. 


We might want to think about the following:

 * Either on banning directly that we delete all remaining data
 * or when updating to a new version, we either fix the banned instances, so it can continue
 * or when updating to a new version, we delete the PI from state, with its related data like timers, messages, etc.
 * or we have maybe a banned process instance processor that is triggered for banned instances, and everytime an event is triggered related to a banned instance it removes the related data from the state (so no new retriggers), as we anyway don't need the data anymore.


Follow-up question: How is this handled for instances with incidents? Can they have the same issue? Do we have a different approach their that can be also use here?

**Comment by berkaycanbc** [comment]
> How is this handled for instances with incidents?

We have a state check on processing timer events that prevents processing timers for elements that is not in active state:
https://github.com/camunda/camunda/blob/28d412a02ec7ead43961fd674889cae31838180e/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/timer/TimerTriggerProcessor.java#L109-L113

> Can they have the same issue?

Yes, we keep writing timer events for elements with incidents until the incident is resolved. But it is expected to be solved with issue https://github.com/camunda/camunda/issues/19292 where we are planning to unsubscribe from elements (probably) right after transitioning to `ELEMENT_COMPLETING` state.

> Do we have a different approach that can be also use here?

I am not sure because the instance banning concept is not part of a BPMN execution flow (as incident does). For example, we directly ban the instance from the state without transitioning it into `banned` state.

@Zelldon don't we keep banned instances to inspect what went wrong? So, if we delete PI data from the state, we lost that after a week from exported records as well.

**Comment by berkaycanbc** [comment]
I moved the issue to blocked until we make a decision on how to fix the problem.

**Comment by Zelldon** [comment]
> I am not sure because the instance banning concept is not part of a BPMN execution flow (as incident does). For example, we directly ban the instance from the state without transitioning it into banned state.

Could that help to introduce such to prevent such issues? If we can't migrate before to an incidents only concept.

> @Zelldon don't we keep banned instances to inspect what went wrong? So, if we delete PI data from the state, we lost that after a week from exported records as well.

Well I doubt that we really doing this. The idea when we implemented this was to keep the state so we can repair this once we have a bug fix for an instance, but we never did that. And there is also something we missed, the commands are ignored, so the actual progress from the log is actual lost. We can't really continue with the instance. (only with some tricks I guess). 

> So, if we delete PI data from the state, we lost that after a week from exported records as well.

Not sure whether I can follow. You mean due to curator/ILM? That is true, but normally you should directly look into such issues right? Afaik we most of them time looked at the log, but I could be wrong.

**Comment by berkaycanbc** [comment]
> Could that help to introduce such to prevent such issues? If we can't migrate before to an incidents only concept.

Do you mean, creating an incident instead of banning the instance? Or introducing a new value type for banning? It might not help in some cases e.g. if we would like to unblock stream processor which is overwhelmed by too many logs on the log stream.

> Well I doubt that we really doing this. The idea when we implemented this was to keep the state so we can repair this once we have a bug fix for an instance, but we never did that. And there is also something we missed, the commands are ignored, so the actual progress from the log is actual lost. We can't really continue with the instance. (only with some tricks I guess).

> Not sure whether I can follow. You mean due to curator/ILM? That is true, but normally you should directly look into such issues right? Afaik we most of them time looked at the log, but I could be wrong.

If these are the case. What about banning the instance as we do now and write a cancel process instance command to the log stream? That way, we will both unblock the stream processor when it is overwhelmed and will terminate the instance. It will also require a modification on the command processing filter of course: https://github.com/camunda/camunda/blob/8f1eb2fc7925e4ffd88d078240042dde9cac8dda/zeebe/engine/src/main/java/io/camunda/zeebe/engine/Engine.java#L126-L130

@Zelldon. Also, @korthout your comments are appreciated here.

**Comment by korthout** [comment]
>banning the instance as we do now and write a cancel process instance command to the log stream

This could fail if the banning occurs as part of cancelation / termination, and end up in an endless loop.

>I feel like we see here again the limitation of the banning of instances, where we should think about again to start to implement a different concept.

@Zelldon I agree completely, but that shouldn't block us from taking a pragmatic solution to fix this issue here, right? Let's discuss the options we have.

Downsides to the options we have:
1. https://github.com/camunda/product-hub/issues/686
   - large investment
   - only resolves this bug when:
     - all banning cases have been replaced by incidents
     - all previously banned instance have been deleted / replaced by incidents
2. move banned instance to quarantined state
   - could fail and hard to maintain ([brittle](https://github.com/camunda/camunda/issues/14213#issuecomment-2128961323))
   - costs state space (disk space + snapshot)
3. delete banned instance from state
   - brittle for same reasons as quarantining banned instances
4. check for banned instances in the `DueDateTimerChecker`
   - has a performance impact on happy path for all timers
   - requires changes in all checkers
5. don't remove skipped commands from command cache
   - fills up command cache if there are many timers for banned instances
   - slows down timer triggering if there are many timers for banned instances

IMO, 4 is really not an option. 1 could be an option, but means we won't resolve this bug until that effort is fully completed. I think we should look for another solution first. 2 and 3 feel hard to maintain, as we always have to remember banned instances when adding new column families that are directly or indirectly related to a process instance. 5 has downsides when there are too many banned instances which would currently be an issue as well.

IMO, option 5 is the most pragmatic solution and reduces the impact of this bug for most cases. Still, options 2 and 3 are better solutions and would be viable if we find a way to maintain this for newly added column families.

My suggestion would be to investigate maintainable solutions to options 2 and 3 first @berkaycanbc.

**Comment by Zelldon** [comment]
>  but that shouldn't block us from taking a pragmatic solution to fix this issue here, right? Let's discuss the options we have.

Well, I never said that. Often enough I prefer pragmatic solutions over others, but if the "solution" has more downsides than benefits then it is not a solution to me. Like keeping an additional cache, which can also grow unlimited and is never cleaned up. 

Personally, I would prefer that we get rid of such banned instances. At least, on newer releases we always clean up the state, during migration. Otherwise, we defragment our state more and more. 

So yes please go ahead and investigate one of the solutions. 👍🏼 

P.S.: BTW only because the solution has a high investment doesn't mean it is bad, sometimes it is necessary to have an investment first to get some gains out of it. Especially if you compare how much you invest in patching the consequences of keeping it :) Furthermore, I think you can do this incrementally, I don't see why you need to cover ALL cases. I guess banning in general will never go away anyway, as we always need something to handle unexpected exceptions.

So enough from me. I will shut up :)

**Comment by berkaycanbc** [comment]
Thanks @korthout and @Zelldon for comments.

@korthout If we will go with separating process instance data in the state, I prefer going with option 3 as it will be easier to maintain. We do not have to create a new banned column family for every process related column family.

I think, Option 5 is still a strong candidate since the issue https://github.com/camunda/product-hub/issues/686 is planned as next. If replacing the existing banning concept will be implemented soon, it might not worth spending time on Option 3. I can check that with product management.

I will spend a time boxed time on the Option 3 to discover its complexity. Otherwise, I would prefer to go with Option 5.

**Comment by berkaycanbc** [comment]
I checked the ways to implement options 2 or 3. We can come up with a solution and force (to some extend) new process instance related entities to be removed when the related instance is banned. One way to achieve this:

1) Create a new abstract class `BannableInstanceState` that has two methods to implement:
```java
public abstract class BannableInstanceState {

  public BannableInstanceState() {
    BannableInstanceManager.register(this);
  }

  abstract void ban(final long processInstanceKey);
}
```
2) Process instance related state classes will extend the above class e.g. `DBJobState extends BannableInstanceState` and will add the functionality (either remove or move to the quarantined column family):

```java
public final class DbJobState extends BannableInstanceState implements JobState, MutableJobState {
   //...

  public DbJobState() {
    super();
    //...
  }
  @Override
  public void ban(final String processInstanceKey) {
    // remove job from state
  }

   //...
}
```

3) Create a class where we manage and perform banning for each process instance related entity:
```java
public class BannableInstanceManager {
  private static final List<BannableInstanceState> bannableInstanceStates = new ArrayList<>();

  public static void register(final BannableInstanceState bannable) {
    bannableInstanceStates.add(bannable);
  }

  public void ban(final long processInstanceKey) {
    for (final BannableInstanceState state : bannableInstanceStates) {
      state.ban(processInstanceKey);
    }
  }
}
```

4) Instantiate `BannableInstanceManager` in `ZeebePartitionAdminAccess` and call the `manager.ban(processInstanceKey)` on banning the instance.

There might be similar alternative solutions to the one above. But they will obviously require more effort and is subject to depreciation when https://github.com/camunda/product-hub/issues/686 is addressed.

If the pragmatic (5th) solution creates issues before we actually implement https://github.com/camunda/product-hub/issues/686, **we can always replace it more easily and go with the solutions like 2 or 3**. Given that, I would like to go with the 5th solution.

**Comment by megglos** [comment]
but back into ready and unassigned (as no capacity)

**Comment by megglos** [comment]
leaving in ready, to be picked up by @berkaycanbc once capacity

**Comment by Zelldon** [comment]
@ana-vinogradova-camunda run into this in an incident afaik https://camunda.slack.com/archives/C05DH1F5TAR/p1726130541559599

**Comment by remcowesterhoud** [comment]
Relevant support case https://jira.camunda.com/browse/SUPPORT-23524
