### ISSUE TITLE
🎯 Export directly to the Elasticsearch Operate indexes

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda#16912]
### Description

* In the Zeebe Elasticsearch exporter, transform Zeebe records into Operate entities and write them into the Operate Elasticsearch indexes
* Keep the current exporting behavior, i.e. writing to Zeebe Elasticsearch indexes, as Tasklist and Optimize still require them
* See the [prototype ticket](https://github.com/camunda/operate/issues/6031) and its implementation to get started
* [Product hub epic](https://github.com/camunda/product-hub/issues/2128)

### Included tasks

- [ ] #18304
- [x] #19006
- [ ] https://github.com/camunda/camunda/issues/23190
- [ ] https://github.com/camunda/camunda/issues/22899
- [ ] #20191
- [ ] #19388
- [ ] #18378 (depends on #16915)
- [ ] #18372 (depends on #16916)
- [ ] #18364 
- [ ] #18306
- [ ] #16920
- [ ] #22747

**Comment by Langleu** [comment]
Hey @ThorbenLindhauer,
any updates on the topic for 8.6 and to aim for a specific alpha?

This change would essentially mean that I could easily run Operate in highly available mode since we're moving the impoter to the exporter layer in Zeebe, right?
I looked for similar epics concerning Tasklist, anything we plan there as well or is it a follow up to however this epic goes?

**Comment by ThorbenLindhauer** [comment]
Hi @Langleu,

> any updates on the topic for 8.6 and to aim for a specific alpha?

Due to the complexity of the implementation we are not targeting a particular alpha at the moment. I'd expect this only to be done with alpha5.

> This change would essentially mean that I could easily run Operate in highly available mode since we're moving the impoter to the exporter layer in Zeebe, right?

I'm not sure what our definition of *highly available mode* is, but assuming that it requires us to have a set of pods where no single pods have special roles: I agree, this should largely resolve with removing the importer. Note however two things:

* We still have the [archiver component](https://docs.camunda.io/docs/self-managed/operate-deployment/importer-and-archiver/) that has similar limitations as the importer (can have only one archiver per Zeebe partition on one pod); this may be less critical though when it comes to availability (the archiver stopping for a while is not noticeable for the end user, unlike the importer)
* The importer will still exist once this epic has been implemented, because we need it during the time of migration (we can't guarantee that the importer has done all its work before the version is updated, so it must continue to run for a bit after the update). I'd expect this time window to be rather short, so probably this is also no larger problem for availability

>  I looked for similar epics concerning Tasklist, anything we plan there as well or is it a follow up to however this epic goes?

Here is the [Tasklist epic](https://github.com/camunda/product-hub/issues/2294), and here the [Optimize epic](https://github.com/camunda/product-hub/issues/2304). We currently have the ambition to also solve it for Tasklist in 8.6, however that plan has a very high risk since we could only start implementing this once most of the Operate work is done. Don't bet on this happening in 8.6. Optimize is only scheduled for 8.7 anyway.

In general, @sdorokhova is the implementation DRI for the Operate part and you can join [#prj-stabilize-operate](https://app.slack.com/client/T0PM0P1SA/C05QBRGMA9F) if you want to address any followups on slack.

Cheers,
Thorben

**Comment by Langleu** [comment]
Thanks for the detailed insights!

**Comment by sdorokhova** [comment]
I will put here the full initial description created by @ThorbenLindhauer . We may use to double-check that all aspects were covered:

### TODO

* Transform the exporting Zeebe records into Operate entities and flush them in batches to Elasticsearch
  * Port the Operate importer's business logic to the exporter; remove ineffieciencies (e.g. unnecessary JSON roundtrips that the importer does today); see also prototype code for inspiration: https://github.com/camunda/zeebe/tree/operate-6031-exporter-prototype/exporters/elasticsearch-exporter
  * Try to find a design that allows for easy testing (e.g. testing record conversion separately from flushing and writing to Elasticsearch; see also the current Elasticsearch exporter's test coverage for what should be covered), extensibility (e.g. when exporting new record types and entities in the future)
  * Merge changes to the same entity within one record batch (e.g. if we see two events for the same Operate entity, do not make two Elasticsearch requests such as an insert and an update, but consolidate the changes into one request, for example on insert)
* Retain the current export behavior to the Zeebe indexes (for Tasklist and Optimize to use)
  * Decide if that should happen in the same (the prototype approach) or in a separate importer
* Find and implement good batch settings
  * How many records/entities should be cached until we make an Elasticsearch bulk request? What should be the timeout setting in low-throughput situations?
* Track process definitions in the exporter
  * To resolve element names by element IDs
  * To resolve element IDs by encoded tree path values (see https://docs.google.com/document/d/1Nh8Jln5_aWIS1O5NnC-SGRblijizDTSujG7zIfc-GOY/edit)
  * Maintain the state, e.g. by:
     * Alternative 1: Persisting it when acknowleding events
     * Alternative 2: Recovering/building the state when the exporter starts (either requesting it from Zeebe or Elasticsearch)
* Let the exporter create the Operate runtime indexes and templates on startup
  * Currently managed by Operate, but keeping it like that would result in a race condition between Operate and Zeebe. Also, the Zeebe exporter now "owns" the Operate runtime schema, being the only writer to it 
  * Probably also needs reworking how demo data is created (but that doesn't have to and probably shouldn't go to the exporter)
* Find meaningful default values for Operate index shards and document how to adapt them to a use case
  * Today, some Zeebe indexes have three shards by default (the busy ones). Operate indexes all have one shard by default. During prototyping, we noticed that the number of shards can have a significant impact on write throughput. Just keeping the Operate default could deteriorate write performance for migrating users. See https://camunda.slack.com/archives/C06F0GLJNFM/p1705944227525519 for what we learned during benchmarking.
* Implement exporter metrics that allow us to understand and meaningfully debug throughput problems
  * We implemented some metrics during prototyping, such as: Time spent in exporter business logic; time spent in JSON serialization; Size of bulk requests (number of Zeebe records that were processed, number of Operate entities, and bytes); Elasticsearch response time; CPU tracking specifically for the exporter threads; size of any maintained state (e.g. process definitions)
* Activate the Operate importer's compatibility mode when the new exporter starts (that was built with https://github.com/camunda/operate/issues/6477)
* Document in the C8 self-managed update guide that users should update from a version 8.5.1 or higher to 8.6.0 (or whichever 8.5. patch ships https://github.com/camunda/operate/issues/6477)
* Optional: Micro-benchmark for profiling the exporter; something that we can use with IntelliJ's profiling features so that we can inspect flamegraphs and find hotspots/inefficiencies in the business logic
   * This was quite useful for developing the prototype (see for example https://github.com/camunda/operate/issues/6031#issuecomment-1881481402)
* Once (largely) implemented, inform @deepthidevaki so that she can evaluate the impact of the exporter changes on multi-region support (see [context](https://github.com/camunda/product-hub/issues/2128#issuecomment-1997683095))

**Comment by Zelldon** [comment]
We have multiple EPICs currently open, I need to clean up a bit of the issues we are having and the duplication of references (it is confusing and high maintenance effort). For actual data check https://github.com/camunda/product-hub/issues/2128 and https://docs.google.com/document/d/1w1VzwyvvBzu0vnjCUj4UcLxTCVae8iMXAMA5_m6xs1s/edit#heading=h.d2n2nlykk7jy
