### ISSUE TITLE
Create a new metric `scheduled-task-duration` to track how long scheduled tasks run and whether any of them block the actor excessively

### ISSUE THREAD

**Issue by mustafadagher** [camunda/camunda#17002]
**Description**
For both `JobTimeOutChecker` and `MessageTimeToLiveChecker` we introduced a new configuration `batch limit` to control the number of jobs processed by the checker in one run before it yields. 
Yielding early would prevent any unanticipated performance degradation, and also would change how long the scheduled tasks actor is blocked by a single pass of that checker.

We are now using `MAX_INT` as a default value for `batch limit`, changing this to an arbitrary value that has a meaning should be done responsively. 
I think the best way to approach this is to monitor both the performance with indefinite limit and the errors if any occurs for some period (say 1-3 months), then if we see any alarming degradation, we would have more data to be able to decide what can be a reasonable limit. we could also experiment there; e.g. change it down bit by bit and see what works best.

However, we have no way to easily detect (or measure) how long the scheduled tasks actually run and so we cannot easily select a fitting number. 

I'm therefore suggesting a new metric `scheduled-task-duration` to track how long scheduled tasks run and whether any of them block the actor excessively.

_Originally discussed in https://github.com/camunda/zeebe/pull/16889#issuecomment-2009178455 and the following comments.

**Comment by megglos** [comment]
ZPA-Triage:
- generic task metric would require alignment with ZDP (e.g. doing that on general scheduler level)
  - in that regard it might be useful to refactor checkers to be based on the same schedule/limiting logic
- impact/use: would allow to determine a good value for the batchLimits (defaults and particular setups/use-cases)
- status quo: one checker could occupy more processing time than others, as the batchLimit is practically unlimited, there is hard limit record batch size => when this is reached the checker will stop and reschedule itself

**Comment by megglos** [comment]
addition by @korthout raising impact to high as we had incidents in the past where timers where not triggered as timely as expected, having the metric would allow us to narrow down why the relevant checker may not run as needed

**Comment by megglos** [comment]
@korthout please link the incidents

**Comment by megglos** [comment]
might be useful here too https://github.com/orgs/camunda/projects/29/views/1?pane=issue&itemId=55359400

**Comment by korthout** [comment]
- https://github.com/camunda/zeebe/issues/16691

**Comment by korthout** [comment]
Talked about this topic a bit more with @oleschoenburg. We both see that the abstraction `Checker` could be part of the stream platform, i.e. it makes sense that the platform offers some way to produce new commands based on periodic state inspection.

We think it would be a good idea for ZPA to start abstracting the concept first and then move it over to the platform. The abstraction is really quite simple:
- check the state (with some context, e.g. index to start at)
- produce some number of commands as a result

ZDP can then help to improve the features of this:
- caching (already provided)
- rescheduling (ability provided, but used by ZPA now; we could move this)
- metrics (this issue)
- configurations to ensure interleaved scheduling with restart with some context (index)
- and even auto-tuning based on logstream pressure as a form of backpressure on the checkers

This also allows us to move the `StreamProcessorLifecycleAware` implementation of these checkers into the stream platform, which is good because the engine shouldn't have to be aware of this lifecycle.

With this abstraction in mind, the only metrics we'd actually be interested in are:
- how often does it run
- how long does it run
- how much did it produce (size of result batch)

**Comment by megglos** [comment]
within scope of this epic https://github.com/camunda/product-hub/issues/2237 , thus moving to backlog
