### ISSUE TITLE
Flaky: io.camunda.zeebe.engine.processing.multitenancy.TenantAwareTimerCatchEventTest.shouldRescheduleTimer

### ISSUE THREAD

**Issue by berkaycanbc** [camunda/camunda#17254]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? once
- Does it block your work? no
- Do we suspect that it is a real failure?

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Error:  Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.461 s <<< FAILURE! -- in io.camunda.zeebe.engine.processing.multitenancy.TenantAwareTimerCatchEventTest
Error:  io.camunda.zeebe.engine.processing.multitenancy.TenantAwareTimerCatchEventTest.shouldRescheduleTimer -- Time elapsed: 5.354 s <<< FAILURE!
java.lang.AssertionError: 

Expecting actual:
  2251799813685258L
to be greater than:
  2251799813685258L

	at io.camunda.zeebe.engine.processing.multitenancy.TenantAwareTimerCatchEventTest.shouldRescheduleTimer(TenantAwareTimerCatchEventTest.java:182)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
</pre>
</details>

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

CI build: [link](https://github.com/camunda/zeebe/actions/runs/8525838605/job/23353747424#step:8:5241)
Downloaded logs: [link](https://drive.google.com/drive/folders/1w0W-3bOZl3B6SAPicMFA4MRHkgE_gYZb)

**Comment by deepthidevaki** [comment]
Occurred again
https://github.com/camunda/zeebe/actions/runs/8790873234
[Uploading Test results for unit tests.zip…]()

**Comment by mustafadagher** [comment]
ZPA-Triage:
- @korthout will take a look

**Comment by korthout** [comment]
I had a look at this flake and can confirm my hypothesis: We're traveling through time before the TimerDueDateChecker is rescheduled.

Let's look at the following logs from a failing test run using the code in `korthout-17254-unflake`:

```
13:13:02.397 [] DEBUG io.camunda.zeebe.engine.processing.multitenancy.TenantAwareTimerCatchEventTest - Increasing time by 1 minute
13:13:02.516 [AsyncProcessingScheduleActor-1] DEBUG io.camunda.zeebe.engine.DueDateChecker[Timer] - Scheduled next execution in 59864 ms: Scheduled[scheduledFor=1714734842380, task=io.camunda.zeebe.stream.impl.ExtendedProcessingScheduleServiceImpl$AsyncScheduledTask@2fdcf836]
13:13:02.524 [] DEBUG io.camunda.zeebe.engine.processing.multitenancy.TenantAwareTimerCatchEventTest - Increased time by 1 minute
13:13:02.524 [] DEBUG io.camunda.zeebe.scheduler.clock.ControlledActorClock - Traveled through time to 2024-05-03T11:14:02.524Z
13:13:02.527 [AsyncProcessingScheduleActor-1] DEBUG io.camunda.zeebe.stream.impl.ExtendedProcessingScheduleServiceImpl - Scheduling task with delay: PT59.864S
13:13:02.527 [AsyncProcessingScheduleActor-1] DEBUG io.camunda.zeebe.stream - Schedule task with delay: PT59.864S
```

The logs show that the test tries to travel through time and, indeed, succeeds in traveling through time before the run of the DueDateChecker is scheduled. 

These logs are produced around the execution of the following lines of code in the test case:

```java
final var timerCreated =
    RecordingExporter.timerRecords(TimerIntent.CREATED)
        .withProcessInstanceKey(processInstanceKey)
        .getFirst();

// when
LOG.debug("Increasing time by 1 minute");
engine.increaseTime(Duration.ofMinutes(1));
LOG.debug("Increased time by 1 minute");
```

The following things happen:
- A timer is created on the log and in the state
- As a side-effect, the DueDateChecker will be scheduled using the scheduling service
- Once the RecordingExporter sees the `Timer:CREATED` event, the test continues with time-traveling
- Both time traveling and scheduling are asynchronous steps that are executed at later moments
- When the `ControlledActorClock` logs `Traveled through time to ..` we know that the time is actually adjusted
- After this log we see the scheduling of the task in 59.864S for the Timer's DueDateChecker occurring

In other words, the DueDateChecker is scheduled almost 1 minute into the future after we have already traveled to time. The DueDateChecker will therefore not run for the created timer during the lifetime of the test case. And this is what we see on the recorded logstream as well:

```
13:13:07.590 [] INFO  io.camunda.zeebe.test - Compact log representation:
--------
	[Timestamp] ['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position] K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
13:13:02.196 C DPLY CREATE         - #01-> -1  -1 - 
13:13:02.242 E PROC CREATED        - #02->#01 K01 - process.xml -> "process" (version:1)
13:13:02.242 E DPLY CREATED        - #03->#01 K02 - process.xml
13:13:02.263 C DPLY CREATE         - #04-> -1  -1 - 
13:13:02.319 E PROC CREATED        - #05->#04 K03 - process.xml -> "RESCHED..PROCESS" (version:1)
13:13:02.319 E DPLY CREATED        - #06->#04 K04 - process.xml
13:13:02.346 C CREA CREATE         - #07-> -1  -1 - new <process "RESCHED..PROCESS"> (default start)  (no vars)
13:13:02.387 C PI   ACTIVATE       - #08->#07 K05 - PROCESS "RESCHED..PROCESS" in <process "RESCHED..PROCESS"[K05]>
13:13:02.387 E CREA CREATED        - #09->#07 K06 - new <process "RESCHED..PROCESS"> (default start)  (no vars)
13:13:02.387 E PI   ACTIVATING     - #10->#07 K05 - PROCESS "RESCHED..PROCESS" in <process "RESCHED..PROCESS"[K05]>
13:13:02.387 E PI   ACTIVATED      - #11->#07 K05 - PROCESS "RESCHED..PROCESS" in <process "RESCHED..PROCESS"[K05]>
13:13:02.387 C PI   ACTIVATE       - #12->#07  -1 - START_EVENT "startEv..575ce56" in <process "RESCHED..PROCESS"[K05]>
13:13:02.387 E PI   ACTIVATING     - #13->#07 K07 - START_EVENT "startEv..575ce56" in <process "RESCHED..PROCESS"[K05]>
13:13:02.387 E PI   ACTIVATED      - #14->#07 K07 - START_EVENT "startEv..575ce56" in <process "RESCHED..PROCESS"[K05]>
13:13:02.387 C PI   COMPLETE       - #15->#07 K07 - START_EVENT "startEv..575ce56" in <process "RESCHED..PROCESS"[K05]>
13:13:02.387 E PI   COMPLETING     - #16->#07 K07 - START_EVENT "startEv..575ce56" in <process "RESCHED..PROCESS"[K05]>
13:13:02.387 E PI   COMPLETED      - #17->#07 K07 - START_EVENT "startEv..575ce56" in <process "RESCHED..PROCESS"[K05]>
13:13:02.387 E PI   SEQ_FLOW_TAKEN - #18->#07 K08 - SEQUENCE_FLOW "sequenc..6bcfac2" in <process "RESCHED..PROCESS"[K05]>
13:13:02.387 C PI   ACTIVATE       - #19->#07 K09 - SERVICE_TASK "task" in <process "RESCHED..PROCESS"[K05]>
13:13:02.387 E PI   ACTIVATING     - #20->#07 K09 - SERVICE_TASK "task" in <process "RESCHED..PROCESS"[K05]>
13:13:02.387 E TIME CREATED        - #21->#07 K10 -  @"timer"[K09]  in <process "K03"[K05]> due T13:14:02.382 reps
13:13:02.387 E JOB  CREATED        - #22->#07 K11 - K11 "type" @"task"[K09] (BPMN_ELEMENT), 3 retries, in <process "RESCHED..PROCESS"[K05]> (no vars)
13:13:02.387 E PI   ACTIVATED      - #23->#07 K09 - SERVICE_TASK "task" in <process "RESCHED..PROCESS"[K05]>
```

Note that the timer is CREATED on position 21 and no TRIGGER command is appended for it. Even though the test has traveled in time to `11:14:02.524` (due to timezones this is 2 hours behind the compacted record log timestamps).

---

So what could we do to unflake this? 
- We could determine the timestamp of actor tasks scheduled through the scheduling service synchronously even for async tasks
- We could allow scheduling tasks at a certain timestamp rather than with a delay
- We can also consider scheduling the DueDateChecker synchronously. Why do we even do this asynchronously?

**Comment by korthout** [comment]
> **We're traveling through time before the TimerDueDateChecker is rescheduled.**
> ..
> So what could we do to unflake this?
> 
> - We could determine the timestamp of actor tasks scheduled through the scheduling service synchronously even for async tasks
> - We could allow scheduling tasks at a certain timestamp rather than with a delay
> - We can also consider scheduling the DueDateChecker synchronously. Why do we even do this asynchronously?

@oleschoenburg Remember that we discussed this case? Do you have any opinions about what's best?

**Comment by oleschoenburg** [comment]
> We can also consider scheduling the DueDateChecker synchronously. Why do we even do this asynchronously?

Because scheduling is only allowed from actor jobs : https://github.com/camunda/zeebe/blob/c57c86f66da2fad38cdb423e2abd22309fae7510/zeebe/scheduler/src/main/java/io/camunda/zeebe/scheduler/ActorControl.java#L187


> We could allow scheduling tasks at a certain timestamp rather than with a delay

This would be my preferred solution.
