### ISSUE TITLE
Tasklist is retuning `null` as item in the permissions array

### ISSUE THREAD

**Issue by vsgoulart** [camunda/camunda#17688]
### Describe the bug

While creating a POC with Entra Id instead of keycloak the current user permissions being populated with `null` values instead of only string

### To Reproduce

1. Deploy Tasklist with Entra Id
2. Open Tasklist

### Actual behavior

The UI breaks and show an error after a while

### Expected behavior

The UI should work

### Environment

Tasklist 8.5 + Entra Id
### Additional context

[Bug report on internal Slack channel](https://camunda.slack.com/archives/C043W5V88M7/p1713816854663589)

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### After solving the issue - Answer and document in the comments the questions below

- [ ] What was the root cause for this bug?
- [ ] Is there anything we should do for the error to not happen anymore?

**Comment by vsgoulart** [comment]
@camunda/hto-backend @marcosgvieira I believe this should be fixed on the backend side since returning `null` in permissions of the current user is against the endpoint contract but I can do a quick fix from the frontend side if it requires too much work for backend too fix it

**Comment by panagiotisgts** [comment]
**Won't Fix**

Front-end permissions filter is sufficient for now.

The upcoming _Identity_ refactor that will include a _commons_ module for authentication will probably cover this case as well, or a relevant ticket will be opened in the opposite case.

This issue is also present in the @camunda/operate service.

Context:
- [HTO slack thread](https://camunda.slack.com/archives/C046XS3GGCR/p1718630098656819)
- [Operate slack thread](https://camunda.slack.com/archives/C9B5270DA/p1718630533886619)
