### ISSUE TITLE
Distinguish failure causes as possible build status for Zeebe CI

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#18856]
**Description**

Now that we have a beautiful dashboard showing us trends on failing builds, we want to be able to drill down and understand why builds are failing. Specifically, I would start with the [following `build_status` & `user_reason` combinations](https://github.com/camunda/camunda/blob/main/.github/actions/observe-build-status/action.yml):

- ✔️ `build_status: failed` & no `user_reason`: generic failure for non-specific cases, e.g. test job fails because of real test failures
- ✔️ `build_status: cancelled` & no `user_reason`: when the build is cancelled explicitly
  - can be simply achieved by using `build_status: ${{ job.status }}`, done in https://github.com/camunda/camunda/pull/20342
- ✔️ `build_status: aborted` & `user_reason: agent-disconnected`: when the runner is disconnected (e.g. crashes, loses connection, etc.), done in https://github.com/camunda/camunda/pull/20703
- ✔️ `build_status: failed` & `user_reason: flaky-tests`: when the build failed due to flaky tests (e.g. test failed, but then passed later)
  - done in https://github.com/camunda/camunda/pull/20342

**Comment by npepinpe** [comment]
ZDP Triage:
- Start with a small amount of states and extend later.
- Unfortunately not much capacity for this at the moment.
- To revisit in 2-3 weeks and see if we can make slow progress on this epic.

**Comment by korthout** [comment]
ZPA triage:
- This appears to be something ZDP is working on
- Removing from our board
- Please re-add if you expect us to do something here

**Comment by cmur2** [comment]
FYI: I rephrased the ticket description a bit to align the requirements with the conventions set by https://github.com/camunda/infra-global-github-actions/tree/main/submit-build-status regarding use of `build_status` (always `failure` even when flaky tests are present since at a first glance the build failed) and `user_reason`.

To make progress on the observability topic of #18210 I addressed some requirements in my work in https://github.com/camunda/camunda/pull/20342 /cc @npepinpe
