### ISSUE TITLE
Copy business logic for `flownode-intance` index from importer to exporter

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#18913]
### Description

As a continuation for https://github.com/camunda/camunda/pull/18886 we need to copy all importer logic to corresponding `ExportHandlers`.

### TODO

* copy logic from `FlowNodeInstanceZeebeRecordProcessor` (latest version from `importer-8_6` module) to several corresponding `ExportHandlers` (probably two: `FlowNodeInstanceFromIncidentHandler` and `FlowNodeInstanceFromProcessInstanceHandler`)

### Additional Information

* check ProcessHandler as an example

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by matt-whiteman** [comment]
@sdorokhova How do you want to handle calculation of the parent tree path? Currently we use the[ElasticsearchFlowNodeStore](https://github.com/camunda/camunda/blob/939f35d6821bfdec34c76811fe75924a0e3a996b/operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/ElasticsearchFlowNodeStore.java#L44) class, but that has multiple components we don't have access to since we don't use spring, and would require manual creation (along with any nested autowired dependencies) and a new FlowNodeStore implementation.

**Comment by matt-whiteman** [comment]
Discussed with @ThorbenLindhauer and decision is we will not calculate the parent tree path here. Tree path field on the entity will be null
