### ISSUE TITLE
startup.sh script overrides helm config

### ISSUE THREAD

**Issue by hamza-m-masood** [camunda/camunda#19114]
**Description**

I am trying to set the following in the helm [configmap](https://github.com/camunda/camunda-platform-helm/pull/1910) for the zeebeGateway:
```
 zeebe:
      gateway:
          host: 0.0.0.0
```

The [startup.sh](https://github.com/camunda/camunda/blob/main/zeebe/docker/utils/startup.sh) script overrides this config with the use of env vars:
```
HOST=$(hostname -i)

if [ "$ZEEBE_STANDALONE_GATEWAY" = "true" ]; then
    export ZEEBE_GATEWAY_NETWORK_HOST=${ZEEBE_GATEWAY_NETWORK_HOST:-${HOST}}
    export ZEEBE_GATEWAY_CLUSTER_HOST=${ZEEBE_GATEWAY_CLUSTER_HOST:-${ZEEBE_GATEWAY_NETWORK_HOST}}

    exec /usr/local/zeebe/bin/gateway

```

We could remove these env vars in the startup.sh script and let the helm configmap have control. I am aware that this might cause potential problems running zeebe outside of helm.

**Comment by hamza-m-masood** [comment]
If the `ZEEBE_GATEWAY_NETWORK_HOST` env var is needed and can't be removed then my PR linked to this issue accommodates for that since I have introduced a new env var in the zeebe gateway helm template.

**Comment by npepinpe** [comment]
The impact of removing these environment variables is that everything will default to bind to 0.0.0.0. The problem with that is that the advertised host will default to use that as well, meaning nodes will tell other nodes to reply to them on 0.0.0.0 (which obviously won't work 😅).

To avoid breaking possibly existing deployments, we need to make sure `advertisedHost` points to the right thing by default unless otherwise specified.

**Comment by npepinpe** [comment]
Alright, this is more complicated than I expected :)

So, in the Dockerfile we also explicitly set an environment variable to override the host of the embedded gateway. This doesn't directly affect the Helm chart by default, since the standalone gateway deployment is default, but would affect it if users are deploying embedded gateways 🙃 

At the same time, the default in the `application.yml` is 0.0.0.0 - that means that if we remove the environment variables from the startup script or the Helm chart, anyone _not_ using the Helm chart will now use 0.0.0.0, which will break the advertising hosts.

What we need:

- A mechanism to select the proper default advertised host, something like:
  - If IPv4 preferred, use the site-local host, otherwise use the first non loopback IPv4 address. If none, use `0.0.0.0`, i.e. `INADDR_ANY`.
  - If IPv6 preferred, use the first non loopback IPv6 address; if none, use `::`, i.e. `INADDR_ANY`.
- Remove setting environment variables in the startup.sh script and Dockerfile that can also be configured via Spring (to allow composition of Spring configuration).
- If the host is set to `INADDR_ANY`, then set `advertisedHost` to the appropriate default advertised host.
