### ISSUE TITLE
The userTask entity should contain taskHeaders

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/camunda#19439]
## Description

Camunda 8 has a concept of `taskHeaders` that allow for adding header fields to a task that is then returned by a job for example.

A user task can also hold these headers and they can be useful to provide meta information about the task.

## Proposal

_A detailed description of your proposed changes or additions to the API guidelines._
_Can also be a link to a document, slides, whiteboard, or anything that is ideally directly commentable._

Add an additional field to the userTask entity that contains the taskHeaders as key-value pairs:

```json
{
  ...
  "headers": {
    "key": "value"
  }
  ...
}
```

## Decisions

_Will be filled in by the project DRIs after a peer review phase._

**Comment by tmetzke** [comment]
@jonathanlukas, could you describe on which level you'd like to see those headers reflected?
They are already reflected in job-based user task entities (since they are jobs that have such headers as you mentioned).
They are also already part of Zeebe user task entities as well.

Are you proposing to expose them in the REST API as well since they are not exposed there yet?
Just trying to understand the intent of this request.

**Comment by jonathanlukas** [comment]
>Are you proposing to expose them in the REST API as well since they are not exposed there yet?
This is the intention. :)

**Comment by tmetzke** [comment]
OK, this will come with the respective endpoints already (like user task search), currently being collected and defined over in this (internal) document: https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA

I think we can close this proposal here since this is already considered in the respective endpoints.

Does that work for you, @jonathanlukas? 🙂

**Comment by jonathanlukas** [comment]
@tmetzke I did not find the field `headers` in the userTask schema: https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.p886hph1hpur

**Comment by tmetzke** [comment]
It's still in definition (which is not obvious from the docs, I'll adjust that). I actually simply forgot them, to be honest. Not sure why I overlooked them. Thanks for the hint 👍
