### ISSUE TITLE
Concurrent maven builds causing failures in CI process.

### ISSUE THREAD

**Issue by EuroLew** [camunda/camunda#19619]
**Description**

A maven build issue maybe related to [concurrent maven builds](https://issues.apache.org/jira/browse/MNG-7868), is blocking a both normal PRs and back porting https://github.com/camunda/camunda/actions/runs/9602339244/job/26482978516?pr=19599. Sometimes the fix is to delete the cache that the built process restores from, however this doesn't always fix it.

**Comment by deepthidevaki** [comment]
@EuroLew Why was this closed? Is it already fixed in some where?

I applied your suggestion https://github.com/camunda/camunda/pull/19613/commits/176a16fb4d145617ce033dda1f292cb546ded24e to the PR that was blocked by this. It was successfully merged. I'm thinking whether we should apply that to all branches. Although I'm not sure whether this really improved the situation or was just a coincidence.

**Comment by EuroLew** [comment]
> @EuroLew Why was this closed? Is it already fixed in some PR?
> 
> I applied your suggestion [176a16f](https://github.com/camunda/camunda/commit/176a16fb4d145617ce033dda1f292cb546ded24e) to the PR that was blocked by this. It was successfully merged. I'm thinking whether we should apply that to all branches. Although I'm not sure whether this really improved the situation or was just a coincidence.

Sorry I thought It was a flake at the time I'll re open it.

**Comment by EuroLew** [comment]
I think it's fine to apply it to all branches, it should hopefully fix the issue, we should probably make sure and apply the commit to the other branches affected by this to see if it fixes it.
