### ISSUE TITLE
Store reference to deployment for deployed resources

### ISSUE THREAD

**Issue by jfriedenstab** [camunda/camunda#19709]
### Description
To support the new [`deployment` binding type](https://github.com/camunda/camunda/issues/19384), Zeebe needs to be able to tell which resources (processes, decisions, forms) were deployed together in the same deployment. Therefore, we should store a reference to the deployment for each deployed resource.

### Acceptance Criteria
- [x] When a deployment request is processed and the contained resources are transformed, the `deploymentKey` is stored as a new property in:
  - [x] `ProcessRecord` (for all processes in a BPMN resource)
  - [x] `DecisionRecord` (for all decisions in a DMN resource)
    - _Note_: It doesn't seem to be necessary to store the deployment key in a `DecisionRequirementsRecord` as well, because only the decision ID is relevant when `deployment` binding is used in a business rule task
  - [x] `FormRecord` (for form resources)
- [x] When the records are persisted in the state, the `deploymentKey` is stored as a new property in:
  - [x] `PersistedProcess`
  - [x] `PersistedDecision`
  - [x] `PersistedForm`
- [x] New column families are added to store:
  - [x] Processes by `processId` and `deploymentKey`
  - [x] Decisions by `decisionId` and `deploymentKey`
  - [x] Forms by `formId` and `deploymentKey`
  - _Note_: To avoid taking up additional storage space, the column families could just store a foreign key (e.g. `processDefinitionKey`) instead of the whole object.
- [x] New methods are added to the state classes to look up the objects from the new column families
(these will be used in #19710)
  - The methods should use a cache to reduce latency.
- [x] The new column families are only filled for new deployments to ensure existing events are replayed deterministically. This should be done by introduction new record and event applier versions.

### Dependencies
- required by #19710

**Comment by korthout** [comment]
I like the described approach. 

> [!NOTE]
> We need to carefully consider how to deal with previously deployed resources. Simply adjusting the event appliers / state classes directly can be dangerous as it may result in non-deterministic event replay. Alternatively, we can increase the version number of the appended events, to ensure newly appended events are applied differently than existing ones. Note that older events are also compacted, so a migration task may be necessary to adjust older data. However, such a task can impact startup/failover performance. All this may mean that we can only fill the proposed column family for newly deployed resources rather than for all existing ones. If so, we should clearly document it as such.

**Comment by jfriedenstab** [comment]
> All this may mean that we can only fill the proposed column family for newly deployed resources rather than for all existing ones.

@korthout Would this actually be a problem? If you want to use the new `deployment` binding type, you'll have to re-deploy all the relevant resources anyway:
- The source process, because you would need to set the new binding type explicitly (e.g. for a call activity).
- The target resource(s), because `deployment` binding only works if those are deployed together with the source process.

So, if I'm not mistaken, there is no need to fill the column family for existing resources.

**Comment by korthout** [comment]
To recap what we discussed:
- existing deployed processes don't require an entry in the new column family (https://github.com/camunda/camunda/issues/19709#issuecomment-2203845295)
- it would be possible to only add the entry to the new column family when `deploymentKey > 0` to ensure existing events are replayed deterministically, but it's easier to understand to use a new record version and new event applier version
- no need to take along #13813 for these classes, but nice to have
- the column family could store the entire record or just a foreign key. The tradeoff is performance vs storage needs
- we should probably cache the entries to reduce the latency of Call Activity, User Task, and Business Rule Task activation

💭 To reduce memory space, you could consider storing the resource keys in the new caches rather than the entire objects and use the existing cache to look them up. This would requires double look up in caches, but can win a bunch a memory space.
