### ISSUE TITLE
Tasklist index prefixes are not correctly setup on OpenSearch

### ISSUE THREAD

**Issue by Belike** [camunda/camunda#19905]
### Describe the bug

When specifying the environment variable CAMUNDA_TASKLIST_OPENSEARCH_INDEXPREFIX (value: "tasklistoos"), indices are not correctly created, and index names are still set as default (tasklist-*). 
Only the 'composed_of' template is correctly set to the given name.

When executing: 
`GET /_index_template/tasklist*`

The following output will be shown:
`{
  "index_templates": [
    {
      "name": "tasklist-task-variable-8.3.0_template",
      "index_template": {
        "index_patterns": [
          "tasklist-task-variable-8.3.0_*"
        ],
        "template": {
          "mappings": {
            "dynamic": "strict",
            "properties": {
              "fullValue": {
                "ignore_above": 8191,
                "type": "keyword"
              },
              "isPreview": {
                "type": "boolean"
              },
              "partitionId": {
                "type": "integer"
              },
              "name": {
                "type": "keyword"
              },
              "tenantId": {
                "type": "keyword"
              },
              "id": {
                "type": "keyword"
              },
              "value": {
                "ignore_above": 8191,
                "type": "keyword"
              },
              "taskId": {
                "type": "keyword"
              },
              "key": {
                "type": "long"
              }
            }
          },
          "aliases": {
            "tasklist-task-variable-8.3.0_alias": {}
          }
        },
        "composed_of": [
          "tasklistoos_template"
        ]
      }
    },
[...]`

I have also tested the behavior against ES locally, where it works correctly. 

### To Reproduce

- Set up a managed OpenSearch cluster (version 2.5) on AWS.
- Utilize helm values 10.2.0 to connect to the cluster.
- Specify the CAMUNDA_TASKLIST_OPENSEARCH_INDEXPREFIX environment variable with the value "tasklistoos".
- Deploy the configuration.
- Execute GET /_index_template/tasklist* in OpenSearch and observe the output.

### Actual behavior

Indices are not created with the specified prefix (tasklistoos-*); instead, they are created with the default prefix (tasklist\*). Only the composed_of template is correctly set to the given name.

### Expected behavior

All indices should be created with the specified prefix (tasklistoos-*), allowing the use of a shared OpenSearch cluster without issues.

### Environment

- Tasklist Version: 8.5.3
- Camunda Helm: 10.2.0
- Amazon OpenSearch Service 2.5

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### After solving the issue - Answer and document in the comments the questions below

- [ ] What was the root cause for this bug?
- [ ] Is there anything we should do for the error to not happen anymore?

**Comment by houssain-barouni** [comment]
The root cause is the following:
- to get the prefix to be used for indices, Tasklist uses [TasklistOpenSearchProperties](https://github.com/camunda/camunda/blob/main/tasklist/common/src/main/java/io/camunda/tasklist/property/TasklistOpenSearchProperties.java) or [TasklistElasticSearchProperties](https://github.com/camunda/camunda/blob/main/tasklist/common/src/main/java/io/camunda/tasklist/property/TasklistElasticsearchProperties.java), depending if Opensearch database is used or not
- Tasklist [reads](https://github.com/camunda/camunda/blob/5d2d5eeb723ac946547b5b8e8548cdeba48c1250/tasklist/common/src/main/java/io/camunda/tasklist/util/TasklistPropertiesUtil.java#L19) `camunda.tasklist.database` system property or system env parameter to know if opensearch being used
- in the helm charts, `camunda.tasklist.database` is defined inside `application.yml` key in a configMap. Which is read a spring property and not system property.
- `getTasklistDatabase()` returns null, and Tasklist defaults [TasklistElasticSearchProperties](https://github.com/camunda/camunda/blob/main/tasklist/common/src/main/java/io/camunda/tasklist/property/TasklistElasticsearchProperties.java), in which the index prefix is the default one (`tasklist`) and not the one defined in `CAMUNDA_TASKLIST_OPENSEARCH_INDEXPREFIX `
- The indices are created with `tasklist` prefix

**Comment by houssain-barouni** [comment]
A workaround is to set `camunda.tasklist.database` as env variable for Tasklist container

``` yaml
env:
  - name: camunda.tasklist.database
    value: opensearch
```
