### ISSUE TITLE
Flaky test shouldBeThreadSafe: io.camunda.zeebe.client.impl.oauth.OAuthCredentialsCacheTest

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#20136]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail?
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**
```
java.lang.RuntimeException: 
java.util.concurrent.ExecutionException: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (File); line: 1, column: 1]
	at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsCacheTest.lambda$shouldBeThreadSafe$4(OAuthCredentialsCacheTest.java:267)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsCacheTest.shouldBeThreadSafe(OAuthCredentialsCacheTest.java:262)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
Caused by: java.util.concurrent.ExecutionException: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (File); line: 1, column: 1]
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsCacheTest.lambda$shouldBeThreadSafe$4(OAuthCredentialsCacheTest.java:265)
	... 3 more
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (File); line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4996)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4898)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3733)
	at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsCache.readCache(OAuthCredentialsCache.java:62)
	at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsCache.computeIfMissingOrInvalid(OAuthCredentialsCache.java:90)
	at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsCacheTest.lambda$shouldBeThreadSafe$1(OAuthCredentialsCacheTest.java:242)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

[Test results for unit tests.zip](https://github.com/user-attachments/files/16127174/Test.results.for.unit.tests.3.zip)

**Comment by matt-whiteman** [comment]
This is a real failure, the file read/write is no longer protected by the synchronized methods. When multiple threads concurrently call methods, it is possible for one thread to attempt to read the cache file while another is overwriting it.

Adding debug statements, the following sequence of events is observed when running the shouldBeThreadSafe test:

****Starting cache read from file (1)
****Starting cache read from file (2)
****Starting cache read from file (3)
****Starting cache read from file (4)
****Starting cache read from file (5)
****Finished cache read from file (4)
****Finished cache read from file (3)
++++Starting file creation
++++Finished creation, Starting file write
****Finished cache read from file (2)
++++Starting file creation
++++Finished creation, Starting file write
****Finished cache read from file (1)
++++Starting file creation
++++Finished creation, Starting file write
++++Starting file creation
++++Finished creation, Starting file write
****Finished cache read from file (0)
++++Starting file creation
++++Finished creation, Starting file write
++++Finished file write
++++Finished file write
****Starting cache read from file (1)
++++Finished file write
****Starting cache read from file (2)
****Starting cache read from file (3)
++++Finished file write
****Finished cache read from file (2)
++++Starting file creation
****Starting cache read from file (3)
++++Finished file write
****Finished cache read from file (2)
++++Starting file creation
++++Finished creation, Starting file write
++++Finished creation, Starting file write
****Starting cache read from file (3)
****Finished cache read from file (2)
++++Starting file creation
++++Finished creation, Starting file write
-----Exception when reading cache file (1)
++++Finished file write
++++Finished file write
++++Finished file write
****Finished cache read from file (0)
++++Starting file creation
++++Finished creation, Starting file write
++++Finished file write

The particular exception encountered is because a read gets no data from the file. This is due to a simultaneous write resetting the file but not yet having a chance to flush its written contents to disk.

Previously, the synchronization on the methods would have allowed each individual read/write to fully complete and not allow another operation to interrupt it.

**Comment by matt-whiteman** [comment]
In addition to the read/write error reported, it may be possible for the in-memory cache to be overwritten by a concurrent readCache that occurs between updating the cache in-memory and writing it to file. Consider:

- ThreadA calls computeIfInvalidOrEmpty, resulting in a file read into memory
- ThreadA computes the credentials for "endpoint1", adds it to in-memory hashmap
- Before ThreadA is able to call writeCache(), ThreadB calls computeIfInvalidOrEmpty which results in another file read into memory
- The updated credentials in-memory are overwritten with the file contents (which do not yet contain "endpoint1")

Additionally,  under the old code, the file does still does not appear to be fully protected, as it can be potentially shared across multiple OAuthCredentialsCache objects and the lock from the synchronized methods was object-level.

**Comment by Zelldon** [comment]
Can we pinpoint why and how it changed?

**Comment by cmur2** [comment]
This affected multiple builds on in merge queue and on `main`:

* https://github.com/camunda/camunda/actions/runs/9838824577/job/27159559917
* https://github.com/camunda/camunda/actions/runs/9886262004/job/27305747178
* https://github.com/camunda/camunda/actions/runs/9883154547/job/27297385508

Was also reported as blocker [via Slack](https://camunda.slack.com/archives/C071KP5BTHB/p1720439794518329).

Given this impact we have to disable this test to not impact CI health and developer experience too much.

**Comment by lenaschoenburg** [comment]
> Can we pinpoint why and how it changed?

https://github.com/camunda/camunda/pull/20065

**Comment by matt-whiteman** [comment]
> Can we pinpoint why and how it changed?

In main it changed in https://github.com/camunda/camunda/pull/20102, looks like it was backported to all versions as well

**Comment by Zelldon** [comment]
I think it makes more sense to revert the change if we know what caused it

**Comment by remcowesterhoud** [comment]
Marking this as a bug instead of a flake. Must be fixed before the next release cycle!

**Comment by megglos** [comment]
One question, do we really need this cache file? I understand it would be useful to carry over accesstokens across application restarts but is this really a problem worth solving?
Haven't checked the history of the cache file introduction but was wondering if this may be a chance to keep it simpler.

**Comment by cmur2** [comment]
Apparently my try to disable/ignore this flaky test in https://github.com/camunda/camunda/pull/20211 was not successful since e.g. https://github.com/camunda/camunda/actions/runs/10005152545/job/27655303351 still failed today citing that specific flaky test as culprit - can any engineer please cross-check my change and suggest an effective way to disable until flakiness is resolved? /cc @remcowesterhoud @lenaschoenburg

**Comment by lenaschoenburg** [comment]
@cmur2 Your change was correct, it's just that someone copied all of the tests and put them in a new module before you added it :upside_down_face: 
The failed test: https://github.com/camunda/camunda/blob/07206c81ce7259f626827aaa4ce6ef7ca0b9529a/clients/java/src/test/java/io/camunda/client/impl/oauth/OAuthCredentialsCacheTest.java#L232-L233

The one with the annotation to ignore: https://github.com/camunda/camunda/blob/07206c81ce7259f626827aaa4ce6ef7ca0b9529a/clients/java/src/test/java/io/camunda/zeebe/client/impl/oauth/OAuthCredentialsCacheTest.java#L232-L235

**Comment by lenaschoenburg** [comment]
Fix is here: https://github.com/camunda/camunda/pull/20370

**Comment by lenaschoenburg** [comment]
> One question, do we really need this cache file? I understand it would be useful to carry over accesstokens across application restarts but is this really a problem worth solving? Haven't checked the history of the cache file introduction but was wondering if this may be a chance to keep it simpler and remove it 😬 .

I generally agree but there are two things to consider:
1. We rate-limit requesting new tokens
2. Short-lived clients such as zbctl might run into this rate limiting quite fast

**Comment by korthout** [comment]
Thanks all for the analysis. IMO, we should not revert the change as the audiences map was not used thread-safe previously. Synchronized methods doesn't resolve that. However, these did ensure that only a single thread could write to the cache file. My changes removed that. 

We can resolve the problem by locking this part specifically with a ReadWriteLock. As an improvement over synchronized methods, this means that multiple threads can read the cache file simultaneously.
