### ISSUE TITLE
Unified REST API: Replace sortOrder Field with Enum in SearchQuerySortRequest

### ISSUE THREAD

**Issue by houssain-barouni** [camunda/camunda#20512]
## Description
We need to update the `sortOrder` field in the `SearchQuerySortRequest` from a string type to an enum with possible values `asc` and `desc` in our OpenAPI specification. The default value should be `asc`. Additionally, we need to ensure that the API validation correctly returns a 400 Bad Request with an appropriate `ProblemDetail` object when an invalid value is provided.

## Acceptance Criteria
- The sortOrder field in the SearchQuerySortRequest is an enum with values `asc` and `desc`, and the default is `asc`.
- The API returns a 400 Bad Request with a ProblemDetail object when an invalid sort order value is provided.
- Unit tests (`ProcessInstanceControllerTest`) are passing/updated with the new validation logic.

## Implementation proposal
We can use an ExceptionHandler on `MethodArgumentNotValidException` to identify the invalid input field

```java
@RestControllerAdvice
public class GlobalExceptionHandler {

    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<ProblemDetail> handleValidationExceptions(MethodArgumentNotValidException ex) {
        for (FieldError error : ex.getBindingResult().getFieldErrors()) {
            if ("sortOrder".equals(error.getField())) {
                // return the problem Detail with the invalid sortOrder
            }
           ...
        }

```

**Comment by tmetzke** [comment]
Unassigning @houssain-barouni for now, anyone can tackle this

**Comment by nathansandi** [comment]
The Open API generator throw an 
`Caused by: java.lang.IllegalArgumentException: Unexpected value 'as'`

We have already the Global Exception (Contorller Advise) over the controllers that deal with error creation
Considering this case,  as I cant create a new advisor, otherwise it creates a conflict, once we cant have 2 global exception controllers

See at: 
https://github.com/camunda/camunda/pull/25570 

So,  it consists in add an "isInvalidSortValue" in order to have an exception straight to this enum, and avoid to have a generic message "Fail to read the value", as it is an unknown exception. 

This is the condition to be true

```
  private boolean isInvalidSortValue(final Exception ex) {
    if (ex instanceof final HttpMessageNotReadableException exception) {
      final var exceptionMessage = exception.getMessage();
      if (exceptionMessage != null
          && exceptionMessage.contains("SearchQuerySortRequest$OrderEnum")) {
        return true;
      }
    }
```

I am open for different suggestions over here 

What do you think @houssain-barouni ?

**Comment by tmetzke** [comment]
@nathansandi, at what point do you get an exception? When generating the model classes from the OpenAPI spec after you turned this into an `enum` there? Or when you execute tests now that provide an erroneous sort order?

I would currently assume that invalid enum values are actually already covered by the global exception handler. The `INVALID_ENUM_VALUE_EXCEPTION_MESSAGE` in the `GlobalControllerExceptionHandler` should already catch such unknown enum values. Defining the enum in the spec and adjusting some test cases might already be enough.

**Comment by nathansandi** [comment]
For visibility, and update the acceptance criteria
the filter will be converted to "ASC" and "DESC" in uppercase 

cc: @tmetzke
