### ISSUE TITLE
Multi instance body finishes with less inner activities than expected

### ISSUE THREAD

**Issue by ana-vinogradova-camunda** [camunda/camunda#20958]
**Describe the bug**

Multi instance body finishes with less inner activities than expected.

**To Reproduce**
Use the below processes ti reproduce the issue:

[MultiInstanceLoop-NOT WORKING.bpmn.zip](https://github.com/user-attachments/files/16562463/MultiInstanceLoop-NOT.WORKING.1.bpmn.zip) - multi instance body finishes with less inner activities than expected, the last multi-instance body finishes with just one activity.

[MultiInstanceLoop-fixed.bpmn.zip](https://github.com/user-attachments/files/16562465/MultiInstanceLoop-NOT.WORKING-fixed.bpmn.zip) - adding a wait time resolves the issue and the last multi-instance body finishes with 5 activities

**Expected behavior**

Both processes should have the same number of inner activities.

**Log/Stacktrace**
[raft-partition.zip](https://github.com/user-attachments/files/16562530/raft-partition.zip)
Process instance key with less inner activities: `2251799813687853` 

**Environment:**
- Zeebe Version: 8.6.0-SNAPSHOT, likely affects older releases down to 8.2 as well

Linked to https://jira.camunda.com/browse/SUPPORT-23118

**Comment by ana-vinogradova-camunda** [comment]
There is a similar issue https://github.com/camunda/camunda/issues/12918 and the fix for it is currently in review. However, the fix does not resolve this issue.

**Comment by megglos** [comment]
bumping severity too high as we identified a prospect at risk to be affected in production and for which the workaround is not applicable

**Comment by remcowesterhoud** [comment]
We did some analysing during a mob-programming session. I've pushed a reproducible test case to [this branch](https://github.com/camunda/camunda/tree/20958-mi-body-analysing).

We saw that some of the `ACTIVATE` commands of the last entry in the input collection got rejected:

```
R PI       ACTIVATE       - #1846->#0182 K0081 - SUB_PROCESS "subprocess2" in <process "process"[K0003]> !INVALID_STATE (Expected flow scope instance with key '2251799813685299' to be present in state but not found.)
R PI       ACTIVATE       - #1847->#0183 K0082 - SUB_PROCESS "subprocess2" in <process "process"[K0003]> !INVALID_STATE (Expected flow scope instance with key '2251799813685299' to be present in state but not found.)
R PI       ACTIVATE       - #1848->#0184 K0083 - SUB_PROCESS "subprocess2" in <process "process"[K0003]> !INVALID_STATE (Expected flow scope instance with key '2251799813685299' to be present in state but not found.)
R PI       ACTIVATE       - #1849->#0185 K0084 - SUB_PROCESS "subprocess2" in <process "process"[K0003]> !INVALID_STATE (Expected flow scope instance with key '2251799813685299' to be present in state but not found.)
```

**Comment by korthout** [comment]
ZPA planning:
- As this is targetted for the upcoming patches, we need to prioritize it
- We want to assign someone already: (@remcowesterhoud, @mustafadagher)

Next step:
- why did the multi-instance body complete before the activate commands were processed? (possibly command batching)

**Comment by remcowesterhoud** [comment]
I had a good debug session with @mustafadagher and we found the root-cause of this problem. We believe it is a bug in the command batch processing mechanism, where the order of command processing is not deterministic.

**What did we observe?**
We noticed that the last command that fit in the command batch was a `ProcessInstanceBatch.ACTIVATE` command. At this point a few interesting things happen:

1. The `ProcessInstanceBatch.ACTIVATE` command's follow-ups don't fit in this command batch anymore
2. The `ProcessingStateMachine` rollbacks the processed commands and reprocesses them. It will process up until this `ProcessInstanceBatch.ACTIVATE` command. Any follow-up command will be processed in a later batch.
3. At some point we process the first Activate command written by the PI batch. Due to batch command processing we immediately process all the followup commands. This includes completing the Multi-instance body.
4. Afterwards we try to process the other activate commands written by the PI batch. These get rejected because the Multi-instance body is already completed.

This means this issue occurs if we can't process all the followup commands of a process instance batch command inside of a single command batch. If you decrease/increase the command batch size sufficiently, the issue doesn't occur.


When a PI batch command fits in the command batch the commands are processed in this order:

```
PI batch activate
subprocess PI activate (1)
subprocess PI activate (2)
subprocess PI activate (3)
subprocess PI activate (4)
subprocess PI activate (5)
startevent PI activate (1)
...
endevent PI complete (1)
subprocess PI complete (1)
start event PI activate (2)
...
endevent PI complete (2)
subprocess PI complete (2)
```


When the PI batch command doesn't fit the order of processing becomes different:

```
PI batch activate (last command in command batch)
subprocess PI activate (1) (first command of new batch)
startevent PI activate (1)
...
endevent PI complete (1)
subprocess PI complete (1)
multi-instance PI complete
startevent PI activate (2) (rejected because MI is completed)
```

**Solutions**

Ideally the command batch processing works in a way that command are always processed in the same order, no matter if that maximum command batch size has been reached or not. @camunda/zeebe-distributed-platform is this behaviour something you are aware of?

For now we can add a check in the `MultiInstanceBodyProcessor` to prevent completing until we have completed all children. We can do this by checking if the number of completed / terminated element instances matches the input collection size.

```java

    if (!childInstanceCreated && stateBehavior.canBeCompleted(childContext)) {
      final var inputCollectionOrFailure = readInputCollectionVariable(element, flowScopeContext);
      final var multiInstanceElementInstance = stateBehavior.getElementInstance(flowScopeContext);
      if (inputCollectionOrFailure.isRight()) {
        final var inputCollectionSize = inputCollectionOrFailure.get().size();
        if (inputCollectionSize
            == (multiInstanceElementInstance.getNumberOfCompletedElementInstances()
                + multiInstanceElementInstance.getNumberOfTerminatedElementInstances())) {
          stateTransitionBehavior.completeElement(flowScopeContext);
        }
      }
    }
  }

```

**Comment by lenaschoenburg** [comment]
I'm not sure I understand the problem correctly yet. Can I rephrase the problem like this?

With batch processing, when the `ProcessInstanceBatch.ACTIVATE` and all of its follow-up fits,  you observe this:
```
PI batch activate
subprocess PI activate (1)
subprocess PI activate (2)
subprocess PI activate (3)
subprocess PI activate (4)
subprocess PI activate (5)
startevent PI activate (1)
```
 
The important part is that all subprocess PIs are activated first.

If the follow-ups don't fit, the  `ProcessInstanceBatch.ACTIVATE` is not processed within that batch but later.
Then you observe the following order:
```
PI batch activate (last command in command batch)
subprocess PI activate (1) (first command of new batch)
startevent PI activate (1)
...
endevent PI complete (1)
subprocess PI complete (1)
multi-instance PI complete
startevent PI activate (2) (rejected because MI is completed)
```
The important difference is that, for some reason, subprocess PIs are not activated all one after another but that we immediately continue processing the first subprocess PI until completion which (wrongfully) completes the multi-instance.

I'm surprised about this behavior. In both cases, batch processing is active. The only difference as far as I understand is that in the first case, the `ProcessInstanceBatch.ACTIVATE` command processed in the middle of batch processing whereas in the second case, the `ProcessInstanceBatch.ACTIVATE` command is the first command that starts batch processing.

Is that correct @remcowesterhoud?

**Comment by remcowesterhoud** [comment]
I just had a chat with @lenaschoenburg. After explaining the problem in person she mentioned it's inherent to the way command batch processing works and it's not a bug. The fact that commands are not processed in a deterministic order is an unfortunate side-effect in cases like the multi-instance, which relies on activation of elements before competion.

> For now we can add a check in the MultiInstanceBodyProcessor to prevent completing until we have completed all children. We can do this by checking if the number of completed / terminated element instances matches the input collection size.

This is the solution we should go with as it's the safest way to determine if we activated all of our child elements before completing the multi-instance body. We should be careful we don't introduce another bug when doing this. For example, what happens if we change the variable used as input collection during all this 🤔
