### ISSUE TITLE
/v2/decision-requirements/search return 200 for Invalid dmnDecisionRequirementsId Data Type

### ISSUE THREAD

**Issue by esraagamal6** [camunda/camunda#21483]
### Describe the bug
When filtering by **dmnDecisionRequirementsId** in the **/v2/decision-requirements/search** endpoint, the system does not correctly handle invalid data types. Specifically, if a numerical value is provided instead of a string for **dmnDecisionRequirementsId**, the system responds with a status code of 200 and an empty list instead of returning a 400 Bad Request error. The expected behavior is to receive a 400 response code indicating that the provided data type is incorrect.

### To Reproduce

- Send a request to the /v2/decision-requirements/search endpoint with the following payload:
```
{
    "filter": {
        "dmnDecisionRequirementsId": 23
    }
}
```
- Observe the response status code and body.

### Actual behavior

The system returns a status code of 200 with an empty list:
```
{
    "items": [],
    "page": {
        "totalItems": 0,
        "firstSortValues": [],
        "lastSortValues": []
    }
}
```

### Expected behavior
The system should return a response with a status code of 400 (Bad Request) indicating that the **dmnDecisionRequirementsId** filter value is invalid.

### Environment

elasticSearch and openSearch

### Additional context

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### After solving the issue - Answer and document in the comments the questions below

- [ ] What was the root cause for this bug?
- [ ] Is there anything we should do for the error to not happen anymore?

**Comment by nathansandi** [comment]
Hello @esraagamal6 
I was rechecking this and it is not a proper a but.

When using Spring’s standard serialization (e.g., Jackson for JSON):
- If you send an integer (123) to a field that is defined as a String in your DTO, Jackson will attempt to convert it to a String during deserialization.

Which means for String type the API accepts Integer (which will be converted to String) or String. Since it is the same data type and compatible. 

For example

This is valid:
```
{
    "filter": {
        "decisionRequirementsId":  "2251799813685256"
    }
}
```

This is also valid:
```
{
    "filter": {
        "decisionRequirementsId":  2251799813685256
    }
}
```

Once both can be serialised/deserialised as String by Jackson.

This happens also with keys, which can be passed as string, since respect the long format. 

For example 
```
{
    "filter": {
            "decisionRequirementsKey": "2251799813685256"
    }
}
```
`decisionRequirementsKey` is long, but as it is possible serialise to long format, the request will work. 


So far, I dont think change all data to "strict" validation patterns would be a good decision, specially considering the maintainability. I can raise this to C8 API team next year. But so far this is not a bug, is an expected behaviour from Open API spec generator.
