### ISSUE TITLE
Failure to push `camunda/zeebe:SNAPSHOT` to DockerHub

### ISSUE THREAD

**Issue by cmur2** [camunda/camunda#21664]
## Description

The [zeebe-ci job](https://github.com/camunda/camunda/blob/bc1dde40ee7511a909710cbc96673bc44e052ce7/.github/workflows/zeebe-ci.yml#L373-L400) to push Snapshot Docker images is during the last 2 days (sporadically?) unable to do because it gets the following error:

> ERROR: failed to solve: failed to push camunda/zeebe:SNAPSHOT: failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://auth.docker.io/token?scope=repository%3Acamunda%2Fzeebe%3Apull%2Cpush&service=registry.docker.io: 401 Unauthorized

### Failures

* https://camunda.slack.com/archives/C013MEVQ4M9/p1724680653951889 (contains discussion)
* https://camunda.slack.com/archives/C013MEVQ4M9/p1724750507800209 (contains unsuccessful reproduction attempt)
* https://github.com/camunda/camunda/actions/runs/10590730363/job/29347448134

## Impact

`camunda/zeebe:SNAPSHOT` [on DockerHub](https://hub.docker.com/r/camunda/zeebe/tags) is potentially outdated and builds on `main` of https://github.com/camunda/camunda appear red.

**Comment by cmur2** [comment]
@Zelldon do you know if it was a sporadic failure or _every_ push of Snapshot Docker images failed and if so, when it started?

**Comment by Zelldon** [comment]
Hey @cmur2 as mentioned [here](https://camunda.slack.com/archives/C071KP5BTHB/p1724833546143439)

I looked into 46 CI failures from main and 15 of them were due to the Docker hub issue. (Not sure whether it is still sporadic, but it is ~31 % :))

Collected failures:

- https://camunda.slack.com/archives/C013MEVQ4M9/p1724680653951889 
- https://camunda.slack.com/archives/C013MEVQ4M9/p1724757455502469 
- https://camunda.slack.com/archives/C013MEVQ4M9/p1724758645628009 
- https://camunda.slack.com/archives/C013MEVQ4M9/p1724769392147159 
- https://camunda.slack.com/archives/C013MEVQ4M9/p1724773629720289 
- https://camunda.slack.com/archives/C013MEVQ4M9/p1724774717043719 
- https://camunda.slack.com/archives/C013MEVQ4M9/p1724780223305179 
- https://camunda.slack.com/archives/C013MEVQ4M9/p1724781593172489 
- https://camunda.slack.com/archives/C013MEVQ4M9/p1724784562639039 
- https://camunda.slack.com/archives/C013MEVQ4M9/p1724790478143009 
- https://camunda.slack.com/archives/C013MEVQ4M9/p1724798179634719 
- https://camunda.slack.com/archives/C013MEVQ4M9/p1724814955493979 
- https://camunda.slack.com/archives/C013MEVQ4M9/p1724823608487539 
- https://camunda.slack.com/archives/C013MEVQ4M9/p1724825019000029

**Comment by cmur2** [comment]
Fix in https://github.com/camunda/camunda/pull/21669
