### ISSUE TITLE
Process instance stuck after resolving incident on parallel gateway

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#22140]
**Describe the bug**

There was an incident on my parallel gateway due to a faulty execution listener. When I tried resolving the incident, the incident disappeared but the process instance did not continue.

**To Reproduce**

<details><summary>Reproducing test case</summary>
<p>

```java
/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Camunda License 1.0. You may not use this file
 * except in compliance with the Camunda License 1.0.
 */
package io.camunda.zeebe.engine.processing.processinstance.migration;

import io.camunda.zeebe.engine.util.EngineRule;
import io.camunda.zeebe.model.bpmn.Bpmn;
import io.camunda.zeebe.protocol.record.Assertions;
import io.camunda.zeebe.protocol.record.intent.IncidentIntent;
import io.camunda.zeebe.protocol.record.intent.JobIntent;
import io.camunda.zeebe.protocol.record.value.JobKind;
import io.camunda.zeebe.test.util.BrokerClassRuleHelper;
import io.camunda.zeebe.test.util.record.RecordingExporter;
import io.camunda.zeebe.test.util.record.RecordingExporterTestWatcher;
import java.util.Map;
import org.junit.ClassRule;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestWatcher;

public class MigrateParallelGatewayTest {

  @ClassRule public static final EngineRule ENGINE = EngineRule.singlePartition();
  private static final String INVALID_EXPRESSION = "missing_var";

  @Rule public final TestWatcher watcher = new RecordingExporterTestWatcher();
  @Rule public final BrokerClassRuleHelper helper = new BrokerClassRuleHelper();

  @Test
  public void shouldResolveIncidentForInvalidExecutionListenerExpression() {
    ENGINE
        .deployment()
        .withXmlResource(
            Bpmn.createExecutableProcess(helper.getBpmnProcessId())
                .startEvent()
                .parallelGateway("and")
                .zeebeExecutionListener(
                    l -> l.start().typeExpression(INVALID_EXPRESSION).retries("0"))
                .endEvent("A")
                .moveToLastGateway()
                .endEvent("B")
                .done())
        .deploy();

    final long processInstanceKey =
        ENGINE.processInstance().ofBpmnProcessId(helper.getBpmnProcessId()).create();

    final var incident =
        RecordingExporter.incidentRecords(IncidentIntent.CREATED)
            .withProcessInstanceKey(processInstanceKey)
            .withElementId("and")
            .getFirst();

    // when
    ENGINE
        .variables()
        .ofScope(processInstanceKey)
        .withDocument(Map.of("missing_var", "listener"))
        .update();
    ENGINE.incident().ofInstance(processInstanceKey).withKey(incident.getKey()).resolve();

    // then
    Assertions.assertThat(
            RecordingExporter.jobRecords(JobIntent.CREATED)
                .withProcessInstanceKey(processInstanceKey)
                .withJobKind(JobKind.EXECUTION_LISTENER)
                .getFirst()
                .getValue())
        .describedAs("Expected to successfully resolve the incident and listen to the execution")
        .hasElementId("and")
        .hasType("listener");
  }
}
```

</p>
</details> 

**Expected behavior**

One of:
- the process instance continues after resolving the incident, 
- or the incident is not resolved, 
- or another incident is raised.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
--------
	['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position] K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
C DPLY         CREATE         - #01-> -1  -1 - 
E PROC         CREATED        - #02->#01 K02 - process.xml -> "process..ression" (version:1)
E DPLY         CREATED        - #03->#01 K01 - process.xml
C CREA         CREATE         - #04-> -1  -1 - new <process "process..ression"> (default start)  (no vars)
C PI           ACTIVATE       - #05->#04 K03 - PROCESS "process..ression" in <process "process..ression"[K03]>
E CREA         CREATED        - #06->#04 K04 - new <process "process..ression"> (default start)  (no vars)
E PI           ACTIVATING     - #07->#04 K03 - PROCESS "process..ression" in <process "process..ression"[K03]>
E PI           ACTIVATED      - #08->#04 K03 - PROCESS "process..ression" in <process "process..ression"[K03]>
C PI           ACTIVATE       - #09->#04  -1 - START_EVENT "startEv..7cf7a1d" in <process "process..ression"[K03]>
E PI           ACTIVATING     - #10->#04 K05 - START_EVENT "startEv..7cf7a1d" in <process "process..ression"[K03]>
E PI           ACTIVATED      - #11->#04 K05 - START_EVENT "startEv..7cf7a1d" in <process "process..ression"[K03]>
C PI           COMPLETE       - #12->#04 K05 - START_EVENT "startEv..7cf7a1d" in <process "process..ression"[K03]>
E PI           COMPLETING     - #13->#04 K05 - START_EVENT "startEv..7cf7a1d" in <process "process..ression"[K03]>
E PI           COMPLETED      - #14->#04 K05 - START_EVENT "startEv..7cf7a1d" in <process "process..ression"[K03]>
E PI           SEQ_FLOW_TAKEN - #15->#04 K06 - SEQUENCE_FLOW "sequenc..08840dc" in <process "process..ression"[K03]>
C PI           ACTIVATE       - #16->#04 K07 - PARALLEL_GATEWAY "and" in <process "process..ression"[K03]>
E PI           ACTIVATING     - #17->#04 K07 - PARALLEL_GATEWAY "and" in <process "process..ression"[K03]>
E INCIDENT     CREATED        - #18->#04 K08 - EXTRACT_VALUE_ERROR Expected result of the expression 'missing_var' to be 'STRING', but was 'NULL'. The evaluation reported the following warnings:
[NO_VARIABLE_FOUND] No variable found with name 'missing_var',  @"and"[K07] in <process "process..ression"[K03]>
C VAR_DOCUMENT UPDATE         - #19-> -1  -1 - VariableDocumentRecord {"tenantId":"<default>","scopeKey":2251799813685251,"variables":{"missing_var":"bar"},"updateSemantics":"PROPAGATE"}
E VAR          CREATED        - #20->#19 K09 - missing_var->"bar" in <process [K03]>
E VAR_DOCUMENT UPDATED        - #21->#19 K10 - VariableDocumentRecord {"tenantId":"<default>","scopeKey":2251799813685251,"variables":{"missing_var":"bar"},"updateSemantics":"PROPAGATE"}
C INCIDENT     RESOLVE        - #22-> -1 K08 - K08
E INCIDENT     RESOLVED       - #23->#22 K08 - EXTRACT_VALUE_ERROR Expected result of the expression 'missing_var' to be 'STRING', but was 'NULL'. The evaluation reported the following warnings:
[NO_VARIABLE_FOUND] No variable found with name 'missing_var',  @"and"[K07] in <process "process..ression"[K03]>
R PI           ACTIVATE       - #24->#22 K07 - PARALLEL_GATEWAY "and" in <process "process..ression"[K03]> !INVALID_STATE (Expected to be able to activate parallel gateway 'and', but not all sequence flows have been taken.)
```

</p>
</details>

**Root cause**

- The process instance doesn't continue because the incident's 'failed command' `ACTIVATE_ELEMENT` is rejected
- It is rejected because 'but not all sequence flows have been taken.'
- But a sequence flow was taken, so how come it looks like there weren't any taken?
- When applied, the `ELEMENT_ACTIVATING` event of the Parallel Gateway cleans up the taken sequence flows

**Comment by megglos** [comment]
ZPA Triage:
- likelihood needs further investigation if also more elements are affected, it seems special for gateways though, it's also unclear if listeners are a likely use case on parallel gateways
- severity mid - you may use instance modification to unblock the process

**Comment by korthout** [comment]
>if also more elements are affected, it seems special for gateways though, it's also unclear if listeners are a likely use case on parallel gateways

The root cause is specific to Parallel and Inclusive Gateways. Other flow nodes are not affected.

**Comment by ce-dmelnych** [comment]
The core issue arises when the `ACTIVATE_ELEMENT` command for a parallel gateway is rejected due to the check `number of taken flows == number of incoming flows`. Upon the first element activation, the method `ProcessInstanceElementActivatingApplier#cleanupSequenceFlowsTaken` is invoked, which resets the number of taken sequence flows for the parallel gateway element.

After resolving the incident related to the expression evaluation of the execution listener job properties, Zeebe tries to activate the element again. At this point, the check `number of taken flows == number of incoming flows` fails because the taken sequence flows count have already been reset by the cleanup logic during the first activation.

**Proposed solution:**
One approach is to move the `cleanupSequenceFlowsTaken` logic from `ProcessInstanceElementActivatingApplier` to `ProcessInstanceElementActivatedApplier` so that it only executes after the element has been fully activated, avoiding premature resets. 

**Discovered problem:**
However, I discovered that when a parallel gateway has multiple incoming flows (e.g., 3) after quick actions (e.g., manual tasks), we can see multiple `ACTIVATE_ELEMENT` commands, the first command is accepted, but the subsequent commands are rejected with `not all sequence flows have been taken`. This behavior is illustrated by the following test:

<details><summary><code> acceptedFirstActivateButRejectSubsequentCommandsDueToSequenceFlowCleanupAfterManualTasks</code></summary>

```java
  @Test
  public void acceptedFirstActivateButRejectSubsequentCommandsDueToSequenceFlowCleanupAfterManualTasks() {
    // given
    ENGINE
        .deployment()
        .withXmlResource(
            Bpmn.createExecutableProcess(helper.getBpmnProcessId())
                .startEvent()
                .parallelGateway("and")
                .manualTask("A")
                .parallelGateway("join")
                .zeebeExecutionListener(l -> l.start().type("my_JOIN_listener").retries("0"))
                .endEvent("final")
                .moveToNode("and")
                .manualTask("B")
                .connectTo("join")
                .moveToNode("and")
                .manualTask("C")
                .connectTo("join")
                .done())
        .deploy();

    // when
    final long processInstanceKey =
        ENGINE.processInstance().ofBpmnProcessId(helper.getBpmnProcessId()).create();
    ENGINE.job().ofInstance(processInstanceKey).withType("my_JOIN_listener").complete();

    // then
    assertThat(
        RecordingExporter.processInstanceRecords()
            .withElementType(BpmnElementType.PARALLEL_GATEWAY)
            .withElementId("join")
            .withProcessInstanceKey(processInstanceKey)
            .limit(r -> r.getIntent() == ProcessInstanceIntent.ELEMENT_COMPLETED))
        .extracting(Record::getIntent, Record::getRecordType)
        .containsSequence(
            tuple(ProcessInstanceIntent.ACTIVATE_ELEMENT, RecordType.COMMAND),
            tuple(ProcessInstanceIntent.ACTIVATE_ELEMENT, RecordType.COMMAND),
            tuple(ProcessInstanceIntent.ACTIVATE_ELEMENT, RecordType.COMMAND),
            tuple(ProcessInstanceIntent.ELEMENT_ACTIVATING, RecordType.EVENT),
            tuple(ProcessInstanceIntent.ACTIVATE_ELEMENT, RecordType.COMMAND_REJECTION),
            tuple(ProcessInstanceIntent.ACTIVATE_ELEMENT, RecordType.COMMAND_REJECTION));
  }
```

</details>

In this case, I'd expect two rejections with the `not all sequence flows have been taken` reason, and the third `ACTIVATE_ELEMENT` command should succeed, just like it does when service tasks are used instead of manual tasks, as seen in this test:

<details><summary><code>shouldRejectTwoActivateAndAcceptThirdAfterServiceTasks</code></summary>

```java
  @Test
  public void shouldRejectTwoActivateAndAcceptThirdAfterServiceTasks() {
    // given
    ENGINE
        .deployment()
        .withXmlResource(
            Bpmn.createExecutableProcess(helper.getBpmnProcessId())
                .startEvent()
                .parallelGateway("and")
                .serviceTask("A", t -> t.zeebeJobType("my_A_task"))
                .parallelGateway("join")
                .zeebeExecutionListener(l -> l.start().type("my_JOIN_listener").retries("0"))
                .endEvent("final")
                .moveToNode("and")
                .serviceTask("B", t -> t.zeebeJobType("my_B_task"))
                .connectTo("join")
                .moveToNode("and")
                .serviceTask("C", t -> t.zeebeJobType("my_C_task"))
                .connectTo("join")
                .done())
        .deploy();

    // when
    final long processInstanceKey =
        ENGINE.processInstance().ofBpmnProcessId(helper.getBpmnProcessId()).create();
    ENGINE.job().ofInstance(processInstanceKey).withType("my_A_task").complete();
    ENGINE.job().ofInstance(processInstanceKey).withType("my_B_task").complete();
    ENGINE.job().ofInstance(processInstanceKey).withType("my_C_task").complete();
    ENGINE.job().ofInstance(processInstanceKey).withType("my_JOIN_listener").complete();

    // then
    assertThat(
        RecordingExporter.processInstanceRecords()
            .withElementType(BpmnElementType.PARALLEL_GATEWAY)
            .withElementId("join")
            .withProcessInstanceKey(processInstanceKey)
            .limit(r -> r.getIntent() == ProcessInstanceIntent.ELEMENT_COMPLETED))
        .extracting(Record::getIntent, Record::getRecordType)
        .containsSequence(
            tuple(ProcessInstanceIntent.ACTIVATE_ELEMENT, RecordType.COMMAND),
            tuple(ProcessInstanceIntent.ACTIVATE_ELEMENT, RecordType.COMMAND_REJECTION),
            tuple(ProcessInstanceIntent.ACTIVATE_ELEMENT, RecordType.COMMAND),
            tuple(ProcessInstanceIntent.ACTIVATE_ELEMENT, RecordType.COMMAND_REJECTION),
            tuple(ProcessInstanceIntent.ACTIVATE_ELEMENT, RecordType.COMMAND),
            tuple(ProcessInstanceIntent.ELEMENT_ACTIVATING, RecordType.EVENT));
  }
```

</details>

**Conclusion:**
If we move the `cleanupSequenceFlowsTaken` method from `ProcessInstanceElementActivatingApplier` to `ProcessInstanceElementActivatedApplier`, we would encounter an issue where the parallel gateway could accept the `ACTIVATE_ELEMENT` command multiple times. This could lead to undesired side effects, such as creating duplicate jobs for the first `start` execution listener.

It seems that the observed behavior—where the parallel gateway accepts the first `ACTIVATE_ELEMENT` command after manual tasks but rejects subsequent commands—should be corrected. The `ACTIVATE_ELEMENT` command should only be accepted after all incoming sequence flows have been taken. Until then, any `ACTIVATE_ELEMENT` commands should be rejected. This would ensure consistent behavior and avoid potential side effects.

Once this behavior is fixed, we can move the `cleanupSequenceFlowsTaken` method to `ProcessInstanceElementActivatedApplier`, as in this case the cleanup will happen after the element has been fully activated.

**Comment by ce-dmelnych** [comment]
Yesterday, during a mob-programming session, we found a better solution to resolve the issue by adding a **process element instance check** before verifying the sequence flow count for the parallel gateway. If the element is already in the `ELEMENT_ACTIVATING` state, it means the sequence flow count check has already been performed, and we can safely bypass it, and allow the process to continue as expected.

Regarding the "discovered problem" mentioned in my previous [comment](https://github.com/camunda/camunda/issues/22140#issuecomment-2382434432): 
This behavior stems from the asynchronous nature of how commands are applied in Zeebe. In the test `shouldRejectTwoActivateAndAcceptThirdAfterServiceTasks`, we had multiple incoming flows to the parallel gateway after service tasks. The presence of intermediate commands and events related to service job creation/completion allowed for a more controlled and ordered application of records. However, in the case of manual tasks, the `ACTIVATE_ELEMENT` command for the parallel gateway is written almost immediately, since the manual task processing doesn’t involve additional commands or events beyond the `ProcessInstanceIntent`.

Special thanks to @korthout , @berkaycanbc , @mustafadagher , and @ana-vinogradova-camunda for another productive mob-programming session that helped us reach this solution.

**Comment by ce-dmelnych** [comment]
Issue was reopened as the [backport PR to `stable/8.6`](https://github.com/camunda/camunda/pull/23374#event-14607978909) was not yet merge due to merge queue build failures (probably, because some infrastructure issues).

**Comment by ce-dmelnych** [comment]
Closing this issue as the [backport PR to `stable/8.6`](https://github.com/camunda/camunda/pull/23374#event-14607978909) was successfully merged.
