### ISSUE TITLE
CamundaExporter should respect the `memory limit` in `bulk` configuration too when batching exported records

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#22869]
The plain elasticsearch exporter flushes the batches periodically, as well as when the bulk size is met. The bulk size is configurable. However, the CamundaExporter can now flush only periodically. The bulkSize configuration is ignored. 

The goal of this issue is to allow CamundaExporter to flush when the buffered entities size crosses the configured threshold, even before the periodical flush.

**Comment by mustafadagher** [comment]
Hi @deepthidevaki, 
In the plain zeebe exporter, there are 3 types of `bulk` configurations: (`delay`, `size`, `memory limit`). Currently, in camunda exporter we respect both the `delay` (how long before flushing) and the size (how many batch items before flushing), but **NOT** the `memory limit` (how much in bytes can the batch request be before flushing).

The later was what I meant when I added this item to the task list of the parent ticket.

But about that, in zeebe how we deal with with bulk items is very different than how we do it in camunda exporter. In zeebe we serialize the record we try to index, and we keep the `byte[]` of the serialized record source in the `bulk operation item` and we use the size of this `byte[]` to determine the size of the complete batch request. 

This is much simpler in zeebe because zeebe exports plain `Record`s, while in our case, we transform records using handlers and export the transformed ones. 

Right now we have no access to the `source` bytes of the transformed entities. And hence, we can't easily determine the size of a `BatchRequest`.

There are one of ways to go around this:
- Remove this `memoryLimit` configuration from camunda exporter
- Rethink how to change the current handlers to serialize entities and keep track of the bytes
Or please advise if you see a third way to do it.

Let me know what you think!

**Comment by Zelldon** [comment]
Top of mind: @mustafadagher what is the return of the Handler? Could this be the size of the corresponding? 🤔 

I guess I need to check the code in more detail to understand how it is working together. Maybe I can do this next week and answer here. :)

**Comment by mustafadagher** [comment]
@Zelldon 
The handler implements some methods from `ExportHandler`, but most importantly, `flush`s an instance ( of an implementation) of `ExporterEntity<>` to a `Batch Request`.

We could add a `size()` method to the the `ExporterEntity` interface, and force every entity to implement it. But I'm not sure if this is feasible for every exporter entity or not. It will also require changes to all current entities in operate/tasklist schemas to implement this new method.

**Comment by Zelldon** [comment]
I will paire with Svetlana and Panos on Monday to bring some new handlers to main. After that I might have a better picture to give better input :) 

But anyhow I don't see this issue as a high prio right now, let me know if you think otherwise.

**Comment by deepthidevaki** [comment]
> Rethink how to change the current handlers to serialize entities and keep track of the bytes

I don't think it is a good idea to add serialization knowledge to the entities.  May be we can keep it simple for now, and just use the the number of cached entities instead of `memory-limit`?

**Comment by mustafadagher** [comment]
> May be we can keep it simple for now, and just use the the number of cached entities instead of `memory-limit`?

Agreed, I'll remove the ability to configure it then next to the changes from https://github.com/camunda/camunda/issues/22866
