### ISSUE TITLE
Create an advanced search concept for the REST API

### ISSUE THREAD

**Issue by tmetzke** [camunda/camunda#23133]
## Description

* We need advanced querying capabilities for the C8 REST API with 8.7 as outlined in https://github.com/camunda/camunda/issues/22584
* There are two ways to achieve this at least:
  * Build proper Advanced Search (in iterations) into the REST API
  * Build the capabilities specifically for certain fields and have a non-breaking integration concept for Advanced Search for 8.8+

## Acceptance criteria

* We have a concept for Advanced Search in the C8 REST API
* We know whether we integrate it directly in 8.7 (with a first set of supported operations) or 8.8+ in a non-breaking way
```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/pull/23530
```

**Comment by tmetzke** [comment]
## Findings (wip)

* A `oneOf` definition for filter attributes, allowing either a primitive type (integer, string, boolean) or an object (advanced operator notation), would generally be possible in OpenAPI. This would allow adding Advanced Search with 8.8+ on spec level without breaking the 8.7 API.
```yaml
  UserTaskFilterRequest:
      description: User task filter request.
      type: object
      properties:
        userTaskKey:
          oneOf:
            - type: integer
              format: int64
            - $ref: "#/components/schemas/LongFilterProperty"
```
* Such a `oneOf` definition can, as of our current knowledge, **NOT** be generated into functional Java code. The `oneOf` definition leads to an interface type for the attributes. The implementation classes of this interface represent the concrete types the REST controller can receive and deserialize into. For the primitive type, no interface implementation is generated though.
  * We could invest time into finding a way to enable/work around this by configuring the generation or providing a custom type ourselves.
  * We could define all properties as plain `object` types and do validation manually in the controllers. However, this leaves no structured information for API users and generators. But it would allow current shortened equals notation (`"field": "value"`) and operator notation (`"field": { "$eq": "value"}`) for the attributes.
* Creating an Advanced Search notation in the spec could be done with `oneOf` definitions as well, e.g.
```yaml
    LongEqFilter:
      description: Equality filter for Long values.
      type: object
      properties:
        $eq:
          type: integer
          format: int64
    LongGtFilter:
      description: Greater than filter for Long values.
      type: object
      properties:
        $gt:
          type: integer
          format: int64
    LongFilterProperty:
      description: Query filter property for Long values.
      oneOf:
        - $ref: "#/components/schemas/LongEqFilter"
        - $ref: "#/components/schemas/LongGtFilter"
    UserTaskFilterRequest:
      description: User task filter request.
      type: object
      properties:
        userTaskKey:
          $ref: "#/components/schemas/LongFilterProperty"
```
* Such a `oneOf` definition can, as of our current knowledge, **NOT** be generated into functional Java code. The generated interface and implementation classes are fine but deserialization does not work. The type to use for deserialization cannot be automatically detected by Spring.

**Comment by danielkelemen** [comment]
## Solution

Working POC: https://github.com/camunda/camunda/pull/23530

- OpenAPI specification contains `oneOf` with primitive and filter object for each properties that support advanced filtering
  - Ref: [`IntegerFilter`](https://github.com/camunda/camunda/blob/ac7ee549feba6b14c6b3113e9f9ce3f68968df57/zeebe/gateway-protocol/src/main/proto/rest-api.yaml#L2818) & [usage in `ProcessInstanceFilterRequest.processDefinitionVersion`](https://github.com/camunda/camunda/blob/ac7ee549feba6b14c6b3113e9f9ce3f68968df57/zeebe/gateway-protocol/src/main/proto/rest-api.yaml#L2882)
- The `openapi-generator` cannot generate the filter and the primitive out of the box. 
  - We turn off the interface creation ([Ref](https://github.com/camunda/camunda/blob/ac7ee549feba6b14c6b3113e9f9ce3f68968df57/zeebe/gateway-rest/pom.xml#L410)) so it generates a class only for the `IntegerFilter`.
  - This is fully usable but doesn't support the implicit primitive equals (eg: `{"filter": 10}`)
- In order to support implicit equals we define `JsonDeserializer`s
  - These can be registered globally, no need to change the OpenAPI or generated classes.
  - The deserializer will transform the implicit equals into the explicit equals format. The rest of the code relies only on the explicit filter class.
  - Ref: [`IntegerFilterDeserializer`](https://github.com/camunda/camunda/blob/ac7ee549feba6b14c6b3113e9f9ce3f68968df57/zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/deserializer/IntegerFilterDeserializer.java)
- Java client uses the explicit filter object, no need for anything special: [Ref](https://github.com/camunda/camunda/blob/ac7ee549feba6b14c6b3113e9f9ce3f68968df57/clients/java/src/main/java/io/camunda/zeebe/client/impl/search/filter/ProcessInstanceFilterImpl.java#L37).
- See advanced search parameter tests: [Ref](https://github.com/camunda/camunda/blob/ac7ee549feba6b14c6b3113e9f9ce3f68968df57/zeebe/gateway-rest/src/test/java/io/camunda/zeebe/gateway/rest/controller/ProcessInstanceQueryControllerTest.java#L466).

**Comment by danielkelemen** [comment]
### IT tests & `dist` Jackson config

Jackson JSON mapper in IT tests and dist configurations is right now configured to use the `operateObjectMapper`, because it's registered with the `MappingJackson2HttpMessageConverter` bean ([Ref](https://github.com/camunda/camunda/blob/main/operate/common/src/main/java/io/camunda/operate/JacksonConfig.java#L73)). This is a problem for us since we need to register our `JsonDeserializer`s manually.

#### Why do we want to register them manually?

1. We generate interface and implementation. We use the interface to register our deserializer for implicit cases and use the implementation to automatically deserialize explicit cases by calling the `ObjectMapper`. Problem: The annotation gets inherited by the implementation so we can't automatically deserialize explicit cases as the `ObjectMapper` would call the same deserializer and end up in a loop. This doesn't happen with manual registration.
2. Adding extra annotation would require an `x-class-extra-annotation` vendor extension in the `rest-api.yaml` which would not be nice for users who want to generate models themselves.

#### Solution

Dist shouldn't use the operate `ObjectMapper`. We need to harmonize Jackson usage in `dist`.

Ideas:
1. Drop the `MappingJackson2HttpMessageConverter` registration.
2. Move the `MappingJackson2HttpMessageConverter` into a separate config and don't scan it in `dist`.
3. Have a `@Primary` `MappingJackson2HttpMessageConverter` registration in dist with default `ObjectMapper`

**Comment by tmetzke** [comment]
Thanks, @danielkelemen, for the PoC efforts here and for documenting decisions and solutions.
I'll close this for now as the concept in general is validated and set.
Solving https://github.com/camunda/camunda/issues/23133#issuecomment-2437206465 will be important but will be an "implementation detail".
