### ISSUE TITLE
CI: add ChatOps command to enable/disable GHA cache usage on a PR

### ISSUE THREAD

**Issue by cmur2** [camunda/camunda#24303]
## Description

For some debugging cases it can be relevant to test CI pipelines with having the GHA cache restore _disabled_ to get the true runtime of jobs assuming a cold cache. That scenario is important sometimes to avoid problems since GitHub clears caches every night and our pipelines might take too long with a cold cache.

This has to be done manually but could be automated (adding `REMOVEME` commits temporarily) via the same approach as in #22483.

Documentation should be added to https://github.com/camunda/camunda/wiki/CI-&-Automation#chatops

## Hints

* @cmur2 is available for questions, pairing and code reviews

**Comment by Kerruba** [comment]
# 🎲 Plan

After some discussion with @cmur2, we came up with the idea of working on two separate issues:

# ⚙️ Issues
## Issue 1: Update cache actions

Since in the monorepo caching is handled by the `setup-maven-cache` and the `setup-yarn-cache`,
those are the places where we should implement the 'disable cache' behavior.
In order to do this, we can update the actions to make it read a label (`no-cahe`) from the PR.
When the `no-cache` state is detected, cache restoration should be skipped.

Working on the centralized actions will avoid the need to modify workflows individually.

## Issue 2: Implement chat commands

We will create a script that will react on a `/?-cache` command in the PR comments. We can think of having a single command,
like `/toggle-cache` that will enable/disable the cache for the PR, or having two separate commands, one to disable the cache
and another to re-enable it (`/disable-cache` and `/enable-cache`).

Either way, the script will be responsible for updating the PR labels and comments accordingly.

### `/disable-cache` command

1. The `/disable-cache` command will add the `no-cache` label to the PR
2. It will also retrigger the workflows to test the code without the cache (could be done by creating a new REMOVEME commit or something similar)

### `/enable-cache` command

1. The `/enable-cache` command will remove the `no-cache` label from the PR
2. It will also retrigger the workflows

# 🏆  Expected outcome

- [ ] A new script is created to deal with chat-ops commands
- [ ] Script will add/remove labels to the PR
- [ ] Centralized actions will read labels from the PR and act accordingly
- [ ] Workflows will be retriggered when the cache is disabled/enabled

**Comment by Kerruba** [comment]
# First iteration

## 🏆 Expected outcome
- [X] A new script is created to deal with chat-ops commands (kindof)
- [X] Script will add/remove labels to the PR
- [X] Centralized actions will read labels from the PR and act accordingly
- [X] Workflows will be triggered automatically when the cache is disabled/enabled

With the current implementation, cache restoration is enabled/disabled based on the presence of a `ci:no-cache` labelon a PR. In particular, if the label is present, cache is not restored in both `setup-maven-cache` and `setup-yarn-cache`.
To add/remove the label and trigger workflows automatically, two commands have been created:

- `/disable-cache`: adds the `ci:no-cache` label and pushes an empty commit to trigger workflows
- `/restore-cache`: removes the `ci:no-cache` label and pushes an empty commit to trigger workflows

With the current implementation, the two commands are actually not required to enable/disable cache, as this could also be done manually by adding/removing the label and pushing to the PR.

I've created a POC repository to test the behavior: 

- https://github.com/Kerruba/poc-disable-cache-command/pull/5

## ❓ Some questions ❓ 

Currently I've opted for a `ci:no-cache` label for triggering the behavior, but that label need to be present on the repository otherwise the action will fail when setting the label. This could be avoided by automatically create the label if not present on the repository, but I'm not sure if we want this to be included in the workflows or should be done differently (i've seen the `labeler` action)

**Comment by cmur2** [comment]
Thanks @Kerruba, I left feedback on https://github.com/camunda/camunda/pull/26086 so we can clarify in one place how to adjust and then the adjustment would also affect https://github.com/camunda/infra-global-github-actions/pull/312

**Comment by Kerruba** [comment]
Thanks @cmur2 for your review. I've updated both of my PRs to include your suggestions. Here a recap:
- [x] I've tested that cache is enabled by default on regular push events and workflow_dispatch in my POC. That should 
- [x] I've updated the actions to use a 'is-cache-enabled' logic rather than a `is-cache-disabled` to improve readability
- [x] I've moved the checks for the branch naming into the `is-cache-enabled` composite action

I was thinking of updating the `setup-maven-cache` composite action with another step to output if current branch is valid for cache-saving or cache-restoring, similarly to what is already done in the `setup-yarn-cache` composite action to simplify the `if` statement, but let me know if is a good idea and if it would make sense to include it with this PR

**Comment by cmur2** [comment]
> I was thinking of updating the setup-maven-cache composite action with another step to output if current branch is valid for cache-saving or cache-restoring, similarly to what is already done in the setup-yarn-cache composite action to simplify the if statement, but let me know if is a good idea and if it would make sense to include it with this PR

Yea that is a good idea!

**Comment by cmur2** [comment]
@Kerruba after merging https://github.com/camunda/camunda/pull/26086 it would be great if you could also add short docs to [this section in the wiki](https://github.com/camunda/camunda/wiki/CI-&-Automation#chatops) (see format I used for `/ci-problems`) 🙇🏼

**Comment by Kerruba** [comment]
@cmur2 I've update the wiki section as requested, I've also updated the "Caching strategy" section with a new sub paragraph mentioning is possible to disable cache on PRs. 
If you think that's not something that we want, please let me know and I'll remove the paragraph (or you can remove it yourself, as you prefer :-) )

**Comment by cmur2** [comment]
That is perfect, thank you!
