### ISSUE TITLE
Assign Priority Interfaces to entities

### ISSUE THREAD

**Issue by marcosgvieira** [camunda/camunda#24464]
Backups for ES/OS are based in [snapshots](https://www.elastic.co/search-labs/blog/how-do-incremental-snapshots-work). In our current scenario we have to take those snapshots in the right sequence to avoid having an inconsistent database when restoring the backup.

This is the sequence we should use to take the snapshots:

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-9bf4123a-7fff-b442-cd16-294d2bd17ab2"><div dir="ltr" style="margin-left:0pt;" align="left">
Name | Indexes
-- | --
camunda_8.6.0-snapshot_part_1_of_7 | Operate-import-position-8.3.0_, tasklist-import-position-8.2.0_optimize-position-based-import-index_v3
camunda_8.6.0-snapshot_part_2_of_7 | Operate-list-view-8.3.0_, tasklist-task-8.5.0_
camunda_8.6.0-snapshot_part_3_of_7 | operate-list-view-8.3.0_*, -operate-list-view-8.3.0_tasklist-task-8.5.0_*, -tasklist-task-8.5.0_
camunda_8.6.0-snapshot_part_4_of_7 | operate-batch-operation-1.0.0_ , operate-operation-8.4.1_ ,
camunda_8.6.0-snapshot_part_5_of_7 | operate-decision-8.3.0_operate-decision-instance-8.3.0_operate-event-8.3.0_operate-flownode-instance-8.3.1_operate-incident-8.3.1_ operate-message-8.5.0_operate-post-importer-queue-8.3.0_Operate-sequence-flow-8.3.0_operate-user-task-8.5.0_operate-variable-8.3.0_, tasklist-draft-task-variable-8.3.0_*, -tasklist-draft-task-variable-8.3.0_, tasklist-task-variable-8.3.0_*, -tasklist-task-variable-8.3.0_
camunda_8.6.0-snapshot_part_6_of_7 | Operate-migration-steps-repository-1.1.0_,operate-web-session-1.1.0_,Operate-user-1.2.0_operate-decision-instance-8.3.0_operate-decision-requirements-8.3.0_operate-metric-8.3.0_operate-process-8.3.0_ tasklist-process-8.4.0_Tasklist-form-8.4.0, Identity-Authorizations, Identity-Users, Identity-Web-Session, Identity-Tenants, Identity-Roles, Identity-Groups, Identity-Mapping
camunda_8.6.0-snapshot_part_7_of_7 | optimize-process-instance-process_05rl6n5_v8, optimize-single-decision-report_v10, optimize-process-overview_v2, optimize-instant-dashboard_v1, optimize-timestamp-based-import-index_v5, optimize-business-key_v2optimize-single-process-report_v11, optimize-combined-report_v5, optimize-dashboard_v8, optimize-dashboard-share_v4, optimize-variable-update-instance_v2-000001, optimize-variable-label_v1, optimize-process-instance-process_1jkjnqs_v8, optimize-terminated-user-session_v3, optimize-settings_v3, optimize-collection_v5, optimize-process-instance-customer_onboarding_en_v8, optimize-report-share_v3, optimize-decision-definition_v5, optimize-tenant_v3, optimize-metadata_v3, optimize-external-process-variable_v2-000001, optimize-process-definition_v6, optimize-alert_v4, optimize-process-instance-variables-test_v8

</div></b>

To achieve that, the current implementation is based in interfaces that sets the priority and order that those snapshots are taken, have a look in this [package](https://github.com/camunda/camunda/blob/78cb2c5deab1507b9dab8c5a5dbbafa81bd89a4a/webapps-schema/src/main/java/io/camunda/webapps/schema/descriptors/backup) and in the current [Operate implementation](https://github.com/camunda/camunda/blob/a39378f36f336346522d85e11e7b4a6c135a4846/operate/webapp/src/main/java/io/camunda/operate/webapp/backup/BackupService.java#L89) to understand this better.

The goal of this task is to assign the correct Interfaces to all indices for Operate, Tasklist, Identity and Optimize as described in the table above.

### Acceptance Criteria

- [ ] To have the correct interfaces being implemented by the indices described in the table above.

**Comment by entangled90** [comment]
To recap the changes that needs to be done:
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-9bf4123a-7fff-b442-cd16-294d2bd17ab2"><div dir="ltr" style="margin-left:0pt;" align="left">
Name | Indexes | Priority
-- | -- | -- 
camunda_8.6.0-snapshot_part_1_of_7 | Operate-import-position-8.3.0_, tasklist-import-position-8.2.0_optimize-position-based-import-index_v3 | 1
camunda_8.6.0-snapshot_part_2_of_7 | Operate-list-view-8.3.0_, tasklist-task-8.5.0_ | 2
camunda_8.6.0-snapshot_part_3_of_7 | operate-list-view-8.3.0_*, -operate-list-view-8.3.0_tasklist-task-8.5.0_*, -tasklist-task-8.5.0_ | 2 w/ matchers
camunda_8.6.0-snapshot_part_4_of_7 | operate-batch-operation-1.0.0_ , operate-operation-8.4.1_  | 3
camunda_8.6.0-snapshot_part_5_of_7 | operate-decision-8.3.0_operate-decision-instance-8.3.0_operate-event-8.3.0_operate-flownode-instance-8.3.1_operate-incident-8.3.1_ operate-message-8.5.0_operate-post-importer-queue-8.3.0_Operate-sequence-flow-8.3.0_operate-user-task-8.5.0_operate-variable-8.3.0_, tasklist-draft-task-variable-8.3.0_*, -tasklist-draft-task-variable-8.3.0_, tasklist-task-variable-8.3.0_*, -tasklist-task-variable-8.3.0_ | 4 & 4 w/ matchers
camunda_8.6.0-snapshot_part_6_of_7 | Operate-migration-steps-repository-1.1.0_,operate-web-session-1.1.0_,Operate-user-1.2.0_operate-decision-instance-8.3.0_operate-decision-requirements-8.3.0_operate-metric-8.3.0_operate-process-8.3.0_ tasklist-process-8.4.0_Tasklist-form-8.4.0, Identity-Authorizations, Identity-Users, Identity-Web-Session, Identity-Tenants, Identity-Roles, Identity-Groups, Identity-Mapping | 5
camunda_8.6.0-snapshot_part_7_of_7 | optimize-process-instance-process_05rl6n5_v8, optimize-single-decision-report_v10, optimize-process-overview_v2, optimize-instant-dashboard_v1, optimize-timestamp-based-import-index_v5, optimize-business-key_v2optimize-single-process-report_v11, optimize-combined-report_v5, optimize-dashboard_v8, optimize-dashboard-share_v4, optimize-variable-update-instance_v2-000001, optimize-variable-label_v1, optimize-process-instance-process_1jkjnqs_v8, optimize-terminated-user-session_v3, optimize-settings_v3, optimize-collection_v5, optimize-process-instance-customer_onboarding_en_v8, optimize-report-share_v3, optimize-decision-definition_v5, optimize-tenant_v3, optimize-metadata_v3, optimize-external-process-variable_v2-000001, optimize-process-definition_v6, optimize-alert_v4, optimize-process-instance-variables-test_v8 | 6 (or 5, as optimize can be done in parallel?)

</div></b>
Changes to be performed:

- create a new BackupPriority: `operate-batch-operation-1.0.0_ , operate-operation-8.4.1_ ` have the same priority as the ones marked in the table with priority 4, which means we need to add another priority to split them into two groups.
- Operate ImportIndex had prio3, now has prio1
- Tasklist TaskTemplate had prio3, now has prio2
- Operate  DecisionIndex was done in the last group (prio4), now it will be done in prio4, but with all the others that were previosly prio3

@marcosgvieira can you confirm that these changes are expected?
/cc @npepinpe

**Comment by entangled90** [comment]
Indices present in the above table, but missing  in `main`:
- optimize-process-instance-process_1jkjnqs_v8 (is this a typo ?)
- optimize-process-instance-customer_onboarding_en_v8
- optimize-process-instance-variables-test_v8

Indices in optimize not present in the above table (from `main`):
- optimize-decision-instance_en

What should I do about this?
@marcosgvieira

**Comment by npepinpe** [comment]
I think @RomanJRW might be able to help you more on the Optimize front.

**Comment by marcosgvieira** [comment]
> Indices present in the above table, but missing both in `main` & `optimize-single-jar`:
> 
> * optimize-process-instance-process_1jkjnqs_v8 (is this a typo ?)
> * optimize-process-instance-customer_onboarding_en_v8
> * optimize-process-instance-variables-test_v8
> 
> Indices in optimize not present in the above table (from `main`):
> 
> * optimize-decision-instance_en
> 
> What should I do about this? @marcosgvieira

I extracted the list of indices directly from ES, so I assume that some sufixes may have been added on creation or something similar, but also not an Optimize expert @RomanJRW or someone from the team probably will be much better on checking those extra indices.

**Comment by marcosgvieira** [comment]
> Changes to be performed:
> create a new BackupPriority: operate-batch-operation-1.0.0_ , operate-operation-8.4.1_  have the same priority as the ones marked in the table with priority 4, which means we need to add another priority to split them into two groups.
> Operate ImportIndex had prio3, now has prio1
> Tasklist TaskTemplate had prio3, now has prio2
> Operate DecisionIndex was done in the last group (prio4), now it will be done in prio4, but with all the others that were previosly prio3

@entangled90 this looks accurate

**Comment by RomanJRW** [comment]
**Static indices:**
Optimize creates a fixed number of indices on startup that will always exist. For example, `[indexPrefix]-single-process-report_vX`.

**Dynamic indices:**
Optimize stores all process instance data in a number of process instance indices. These indices are named `[indexPrefix]-process-instance-[processDefinitionKey]_vX`, whereby the prefix is configured in Optimize and the `vX` indicates the index version. An example would be `optimize-process-instance-variables-test_v8` for a process with key `variables-test` and prefix defined as `optimize` (which is the default, and what we use internally). All process instance data for that process will be stored in that index. These indices are not created on Application startup, but rather when the Optimize importer first sees data relating to a given process - so we call them dynamic

**This is relevant because:**
- An index like `optimize-process-instance-variables-test_v8` is something that will not exist for most customers (only those with a process key `variables-test` deployed)
- Optimize cannot know in advance how many of these dynamic indices will exist, nor what their names will be

**Status quo:**
Optimize depends on backups happening in two phases. Phase 1 is backing up the import indices, and Phase 2 is backing up all other indices (including the dynamic process instance ones described above).
Currently, it does this by querying the DB for all Optimize indices (static and dynamic), and filters for the import indices to trigger first, then subsequently triggers another backup for the rest.

**Other notes:**
- Optimize loads up one data set for customers to onboard with. It does not come from Zeebe and is not really deployed anywhere. This is the data inside `[indexPrefix]-process-instance-customer_onboarding_en_vX`
- In 8.6, Optimize deleted some of its indices. I don't know when the above table was populated, but it _might_ be that some of the static indices no longer exist

Bringing it back to your questions more directly...

>
> Indices present in the above table, but missing both in main & optimize-single-jar:
>
> optimize-process-instance-process_1jkjnqs_v8 (is this a typo ?)
> optimize-process-instance-customer_onboarding_en_v8
> optimize-process-instance-variables-test_v8

I assume this is because the original table was populated by an Optimize instance that had the customer onboarding dataset enabled, and that had two processes deployed (with keys `variables-test` and `process_1jkjnqs`). Your local deployment likely does not match these conditions.

> Indices in optimize not present in the above table (from main):

> optimize-decision-instance_en
> What should I do about this?

This is a slightly stranger case. Optimize has never supported decision analysis in C8 so I would never expect this index to be created. I would be happy to pair with you to look into this more if it helps. Generally speaking, this index can be ignored from backups because it should not be present in C8 at all.

I hope that helps, let me know if you have any questions or need clarification

**Comment by entangled90** [comment]
> optimize-decision-instance_en
I may have wrongly constructed the name of the index, but I was referring to the class [DecisionInstanceIndex](https://github.com/camunda/camunda/blob/main/optimize/util/optimize-commons/src/main/java/io/camunda/optimize/service/db/schema/index/DecisionInstanceIndex.java) which is the only one without a backup priority.

That seemed strange, so I wanted to double check with you. Should I add Prio6 to this class as well?

**Comment by RomanJRW** [comment]
@entangled90 
The decision instance index is another example of a dynamic index that Optimize can create (exactly the same as process instance indices).

However, this is legacy from Optimize in the C7 world and in C8, Optimize should never actually create such an index. I expect that one day we will add Decision analysis to C8, but it's not on the roadmap right now.

I think to keep your scope reduced, you should just safely ignore the DecisionInstanceIndex given that we never expect it to exist
