### ISSUE TITLE
Potential lost information in Camunda exporter

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#24736]
### Description

Every record that is exported with Camunda exporter is processed by several [ExportHandlers](https://github.com/camunda/camunda/tree/main/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers). The entity is cached until [`flush` method is called](https://github.com/camunda/camunda/blob/e78dd201e46fbd3897e44b64bd78b7693916dd46/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/store/ExporterBatchWriter.java#L62). Flush from the latest called handler will be called. But in case the entity already exists in Elastic, only part of the fields will be updated, those updated in the last handler. We may lose some other field values, that were set in previous handlers.

### TODO

* we need to find a way to properly accumulate all the updates from all the called handlers, when performing flush

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by Zelldon** [comment]
@sdorokhova is this an assumption or were you able to reproduce this? 🤔

**Comment by Zelldon** [comment]
:fyi2: I had a deeper look at https://github.com/camunda/camunda/issues/24736

Triage:

- Severity: Critical; as we lose data/information
- Impact: Data is not complete in ES.
- Likelihood: Low-Mid; It happens when an entity/document is already stored in ES. More likely on completion

Details:

- In the ExporterBatchWriter we pass records to all handlers that accept the value type and want to handle the given record
- The results of each handler are stored in a cache (with the corresponding handler)
- Results are identified by id and entity type
- On flush, we call for each cached entity the corresponding handler to flush

**Expectations (previous):**

- The export handlers have a one-to-one mapping to an entity. 
- This means per entity we have one specific handler, and vice-versa
- It could happen that the same handler is called multiple times during a batch because we see multiple events related to the same entity (ACTIVIATED-COMPLETED, etc.)

Problem:

- We have implemented multiple handlers that reuse entity types, even if they set only a subset of properties. 
- Consequence:
- As they use the same type, and in some cases even generate the same id only the last handler wins. Flush is only called on the last one, which consumed the record.
- Only partial data is updated.
- On creation (missing document) this is not an issue because we use mostly upserts, which uses the complete entity object. Here all data is written.

Possible solutions:

- Avoid caching
  - We could remove the caching and call for all handlers the respective flush method
  - This would work, but will cause more queries and also defragmentation as smaller segments are created in ES (possible performance issue)
- We merge somehow the properties for the same entity in the BatchRequest; 
  - Implementation might be rather complex and might need an additional layer between BatchRequest and specific implementations 
- We don't reuse entity types
  - As the handlers are actually quite specific to certain records and only set a subset of properties in the entities (fex ListView), we could create separate entities
  - The subset entities can still be used to upsert documents in the respective indices, even if they contain a subset of properties (similar to what anyway happens when sending JSON data)

I discussed this with @roman.smirnov and our tendency is to approach 3. We can also verify via UT whether each handler has its specific entity, to avoid this in the future.

I'm open to more feedback and ideas if you have any.
