### ISSUE TITLE
Modify the snapshot backup file pattern to "webapps"

### ISSUE THREAD

**Issue by entangled90** [camunda/camunda#25481]
Snapshots were saved ~~in different repositories~~ with different file name patterns  for each application, but after the backups for webapps are unified we need to rename it. 
The ~~repository~~ file name pattern at the start of the file should be  "webapps".

Same for the names of the snapshots inside the repository, we now have  `OperateSnapshotNameProvider` and `TasklistSnapshotNameProvider`. They must be combine into one.

Previously the pattern for snapshots was either:
- `camunda_operate_{backupId}_{prefix}{version}_part_{index}_of_{count}`
- `camunda_tasklist_{backupId}_{prefix}{version}_part_{index}_of_{count}`
Change it to:
- `camunda_webapps_{backupId}_{prefix}{version}_part_{index}_of_{count}`

\cc @npepinpe @marcosgvieira

**Comment by npepinpe** [comment]
Hm, so this is OK in terms of backwards compatibility because anyway backups are tied to versions, correct? So a pre-existing back up wouldn't be useful anyway for 8.7+, so it should be fine changing repository.

The only thing I could imagine is that snapshots in ES are incremental, so you would be losing on this - this means for customers with lots of the data, the initial snapshot could be very expensive when we rename the repository.

Note I'm not ES expert, so we should verify this. This may also be a trade-off we're willing to accept. Personally, I would avoid it if possible though: my assumption is Operate will typically have more data (ignore Optimize for now), so it may be safer to keep Operate's repository for pre-existing installations.

We can use a new repository for fresh installs. Or they may be an alternative I'm not aware of (e.g. rename an ES repository to keep the incremental data). Or maybe the incremental data doesn't matter as much as I think? :thinking:

**Comment by entangled90** [comment]
We coulde detect the pattern from existing backups? If none is found then use webapps, otherwise keep operate.

**Comment by npepinpe** [comment]
@marcosgvieira what do you think? Should we worry about this?

**Comment by entangled90** [comment]
Regarding incremental backups, when we will release 8.7 old backups will not be used, so we can also change the prefix as well, right?

**Comment by npepinpe** [comment]
It's not so much about not using them, but that ES takes incremental ones - though I don't really know how it works under the hood, and maybe it doesn't matter much.

Would love to know what @marcosgvieira thinks, but in the meantime, we can assume it's OK to change snapshot repository for now.

**Comment by npepinpe** [comment]
We should still figure out how we want to handle the standalone deployments where someone would configure different snapshot repository names, as it could lead to broken back ups :s

**Comment by entangled90** [comment]
I think I confused two different items:
- repository name
- pattern of the filename backups

This issue is not about the repository, but about the naming convention of the backups files.

The repository name always come from the configuration.

**Comment by npepinpe** [comment]
The file names are likely fine to change :+1:

**Comment by entangled90** [comment]
I'll make the change then :+1:
