### ISSUE TITLE
Identity records are not copied properly

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#25620]
Identity related records such as:
- `UserRecord`
- `TenantRecord`

implement a `wrap` method such as this:

https://github.com/camunda/camunda/blob/1e4f427b9d6c1ad63b2753e56ec021f7b7cda1a4/zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/user/UserRecord.java#L40-L47

This in itself would be fine but unfortunately it is used as if this would do a `copy`.

For example, `PersistedUser#copy` ends up eventually using `UserRecord#wrap`.

Additionally, `TenantRecord` defines it's own `copy` method that is broken in the same way.

**Comment by korthout** [comment]
We should probably just use [`BufferReader.copyFrom(BufferWriter)`](https://github.com/camunda/camunda/blob/94ac09a7965bfe1902798f42733f11d0a3897621/zeebe/util/src/main/java/io/camunda/zeebe/util/buffer/BufferReader.java#L33-L35) which is available for all concrete records.

🤔 Time to remove all `wrap` methods!

**Comment by korthout** [comment]
I've found a bunch more places where buffers are directly passed to the other object in the `wrap` method. 

https://github.com/camunda/camunda/blob/1c300aa69cc92e949adc3bfbb41f91a74a8ed2b1/zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/incident/IncidentRecord.java#L66-L72

https://github.com/camunda/camunda/blob/1c300aa69cc92e949adc3bfbb41f91a74a8ed2b1/zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/job/JobRecord.java#L138-L141

https://github.com/camunda/camunda/blob/1c300aa69cc92e949adc3bfbb41f91a74a8ed2b1/zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/job/JobRecord.java#L113-L131

https://github.com/camunda/camunda/blob/1c300aa69cc92e949adc3bfbb41f91a74a8ed2b1/zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/message/MessageCorrelationRecord.java#L50-L53

https://github.com/camunda/camunda/blob/1c300aa69cc92e949adc3bfbb41f91a74a8ed2b1/zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/message/MessageRecord.java#L47-L53

https://github.com/camunda/camunda/blob/1c300aa69cc92e949adc3bfbb41f91a74a8ed2b1/zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/message/MessageStartEventSubscriptionRecord.java#L52-L60

https://github.com/camunda/camunda/blob/1c300aa69cc92e949adc3bfbb41f91a74a8ed2b1/zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/message/MessageSubscriptionRecord.java#L52-L60

https://github.com/camunda/camunda/blob/1c300aa69cc92e949adc3bfbb41f91a74a8ed2b1/zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/processinstance/ProcessInstanceRecord.java#L93-L95

https://github.com/camunda/camunda/blob/1c300aa69cc92e949adc3bfbb41f91a74a8ed2b1/zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/message/ProcessMessageSubscriptionRecord.java#L58-L68

https://github.com/camunda/camunda/blob/1c300aa69cc92e949adc3bfbb41f91a74a8ed2b1/zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/signal/SignalRecord.java#L34-L36

https://github.com/camunda/camunda/blob/1c300aa69cc92e949adc3bfbb41f91a74a8ed2b1/zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/signal/SignalSubscriptionRecord.java#L43-L46

https://github.com/camunda/camunda/blob/1c300aa69cc92e949adc3bfbb41f91a74a8ed2b1/zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/usertask/UserTaskRecord.java#L110-L137

💭 IMO, the `wrap` method seems to have simply not been intended to make a deep copy. The buffer wrapping is likely intended to just be fast (equivalent to the set methods of int/long/etc which are implemented with simple field assignment). This can be useful when quickly passing the values into a object used by the state classes. For example, see [`DbSignalSubscriptionState.put`](https://github.com/camunda/camunda/blob/1c300aa69cc92e949adc3bfbb41f91a74a8ed2b1/zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/signal/DbSignalSubscriptionState.java#L72-L73) which uses `wrap` in [`SignalSubscription.setRecord`](https://github.com/camunda/camunda/blob/1c300aa69cc92e949adc3bfbb41f91a74a8ed2b1/zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/signal/SignalSubscription.java#L31-L33).

💭 Looking at the usage of the `wrap` methods, I notice that a lot of them are unused. The once that are used, are likely used in ways that have so far been safe.

⚠️ However, compensation has unsafe usage:

https://github.com/camunda/camunda/blob/1c300aa69cc92e949adc3bfbb41f91a74a8ed2b1/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnCompensationSubscriptionBehaviour.java#L287-L292

⚠️ There are also somewhat unsafe usages in other important classes like when taking a sequence flow. They are safe because the result is immediately written to the state/log which are both making hard copies. However, the record value in the context is definitely changed after a call to this method. For safety, this could be a good place to use `copyFrom` instead.

https://github.com/camunda/camunda/blob/1c300aa69cc92e949adc3bfbb41f91a74a8ed2b1/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/behavior/BpmnStateTransitionBehavior.java#L295-L304

⚠️ I also found a wrap method that isn't complete, but it's unused currently:

https://github.com/camunda/camunda/blob/1c300aa69cc92e949adc3bfbb41f91a74a8ed2b1/zeebe/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/resource/ResourceDeletionRecord.java#L22-L29

**Comment by korthout** [comment]
I checked the migration of compensation events, which does not produce a bug because the wrapped record is only used in a written event immediately after the wrap and is then discarded. Since the append is safe (both to the log and state), this usage does not produce a bug:

```
E COMPENSATION_SUB MIGRATED          - #51->#49 K12 - CompensationSubscriptionRecord {"compensationHandlerInstanceKey":-1,"compensableActivityInstanceKey":2251799813685257,"processDefinitionKey":2251799813685252,"compensableActivityId":"C","compensationHandlerId":"undoC","throwEventInstanceKey":-1,"compensableActivityScopeKey":2251799813685253,"tenantId":"<default>","variables":{},"processInstanceKey":2251799813685253,"throwEventId":""}
E COMPENSATION_SUB MIGRATED          - #52->#49 K17 - CompensationSubscriptionRecord {"compensationHandlerInstanceKey":-1,"compensableActivityInstanceKey":2251799813685262,"processDefinitionKey":2251799813685252,"compensableActivityId":"D","compensationHandlerId":"undoD","throwEventInstanceKey":-1,"compensableActivityScopeKey":2251799813685253,"tenantId":"<default>","variables":{},"processInstanceKey":2251799813685253,"throwEventId":""}
```
