### ISSUE TITLE
Allow to provide a preconfigured elastic client to elasticsearch exporter

### ISSUE THREAD

**Issue by menski** [camunda/camunda#5274]
**Is your feature request related to a problem? Please describe.**

As a user I want to support a custom authentication to elasticsearch which cannot be generalized. I would like to be able to configure an ES client myself, and hand it to the elasticsearch exporter.

**Describe the solution you'd like**

Extension point which allows the user to add a jar to the shared libraries which can be hooked in the elasticsearch exporter initialization, the extension point returns an es client which is then used by the exporter.

**Describe alternatives you've considered**

Implementing a own exporter, or modifying the existing exporter. This has the downside of maintaining multiple code bases for the same purpose.

**Comment by tjayr** [comment]
There was some discussion(@Zelldon) on Slack about exporting to Opensearch. As a POC I modified this exporter and swapped out the Elasticsearch rest client. (https://github.com/tjayr/zeebe-opensearch-exporter).  While the basic functionality works, I don't feel creating a separate project to add this support is the correct approach. 

I would suggest that the extensions point idea behind this feature request could also be used to add Opensearch support. An Opensearch implementation could be packaged within this exporter or could be plugged in externally.

Borrowing from the proposed solution outlined @ https://github.com/camunda/zeebe/issues/2004#issuecomment-727773597 adding this support could broadly look something like this:

Extract an interface from `io.camunda.zeebe.exporter.ElasticsearchClient`

```java
package io.camunda.zeebe.exporter.spi;

public interface SearchClient extends AutoCloseable {

  @Override
  void close() throws IOException;
  void index(Record<?> record);
  void flush();
  boolean shouldFlush();
  boolean putIndexTemplate(ValueType valueType);
  boolean putComponentTemplate();
}
```
Create a service provider interface

```java
package io.camunda.zeebe.exporter.spi;

public interface SearchClientProvider {
  String getId();
  SearchClient create(ElasticsearchExporterConfiguration configuration);
}
```

A SearchClientProvider is implemented that creates the existing ElasticsearchClient (note this also loads the rest client from a service loader, which is described later)

```java
public class ElasticsearchClientProvider implements SearchClientProvider {

  @Override
  public String getId() {
    return ElasticsearchClientProvider.class.getName();
  }

  @Override
  public SearchClient create(final ElasticsearchExporterConfiguration configuration) {
    final ServiceLoader<RestClientProvider> esProvider =  ServiceLoader.load(RestClientProvider.class);

    final var provider =  esProvider.stream()
            .filter p -> p.get().getId().equals(configuration.getClientConfiguration().getImplementation())
            .findFirst()
            .orElseThrow( () -> new ElasticsearchExporterException( "No implementations found..."))
            .get();

    return new ElasticsearchClient(configuration, provider);
  }
```

`io.camunda.zeebe.exporter.ElasticsearchClient#createClient()` is updated to use the SearchClient interface and service loader:

```java
  protected SearchClient createClient() {

    final ServiceLoader<SearchClientProvider> loader =  ServiceLoader.load(SearchClientProvider.class);
    final var provider =  loader.stream()
            .filter( s ->  s.get().getId().equals(configuration.getClientConfiguration().getImplementation()))
            .findFirst();
    return provider.get().get().create(configuration);
  }
```

The same concept could apply to loading different RestClient implementations.

Create RestClientProvider

```java
package io.camunda.zeebe.exporter.spi;

public interface RestClientProvider<T> {
  String getId();
  RestClient<T> create(ElasticsearchExporterConfiguration configuration);
}

package io.camunda.zeebe.exporter.spi;

public interface RestClient<T> {
  T get();
}
```

`io.camunda.zeebe.exporter.RestClientFactory` is refactored to implement the `RestClientProvider` interface to provide the default Elasticsearch RestClient implementation.

```java
package io.camunda.zeebe.exporter.spi.impl;

public class ElasticsearchRestClientProvider
    implements RestClientProvider<org.elasticsearch.client.RestClient> {
   ...
}
```

The constructor of the `ElasticsearchClient` is updated to take a `RestClientProvider` instead of the direct dependency on Elasticsearch RestClient. 

The configuration class would also need to be updated to include configuration options (with Elasticsearch as the default)

```yaml
        args:          
          client:
            implementation: a.b.c.OpensearchClientProvider
            restProvider: x.y.z.OpensearchRestClientProvider
```

**Comment by npepinpe** [comment]
Closing this - we're actively working on this, so expect to see something in the next release(s) :+1:
