### ISSUE TITLE
As a user, I want to get a Zeebe's container healthcheck via docker inspect

### ISSUE THREAD

**Issue by aivinog1** [camunda/camunda#8481]
**Is your feature request related to a problem? Please describe.**
I'm using Zeebe docker containers to make some experiments. And it is so convenient to me if a health status will be in docker inspect.

**Describe the solution you'd like**
I think that we should implement a Docker health check for the container, [like this](https://docs.docker.com/engine/reference/builder/#healthcheck). We can query the actuator endpoints for example.

**Describe alternatives you've considered**
I can't find alternatives :(

**Comment by npepinpe** [comment]
Sounds good. It seems like this is more of a liveness check? It's probably still OK - the only issue with it is that:

1. The actuator can be disabled (but I guess that's OK-ish)
1. In the Dockerfile, we don't know if the image is a gateway, a broker, or both :smile:

The last one is a limitation with the fact we bundle the gateway and the broker as the same image, which is obviously something we should change long term, but we can't work around it for this particular issue (yet).

**Comment by aivinog1** [comment]
Hey @npepinpe. Thanks for the reply, but I can't see a difference between calling Actuator's health endpoint on gateway or broker or broker with embedded gateway 🤔 . We just call `/actuator/health` and that's all as can see. Do I miss something? :)

**Comment by npepinpe** [comment]
The endpoint is the same, but the behavior is a bit different, which is why I wasn't sure if it fits Docker's definition of healthcheck for both applications. If I understand correctly, the healthcheck failing will cause the container to be restarted, correct? If the container is a gateway, the health check can become unhealthy if there is no known leader. Restarting the container isn't particularly useful though, in this case. But maybe I misunderstood how the health check works.

**Comment by npepinpe** [comment]
Closing for now. Open to suggestions, but it might be worth looking into this after the C8 streamlining.
