### ISSUE TITLE
Follower doesn't send response back if append fails

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#8612]
**Describe the bug**

Taking a look at the code I saw that if the follower is failing to append it just flush the appended records and stops with the appending 

https://github.com/camunda-cloud/zeebe/blob/develop/atomix/cluster/src/main/java/io/atomix/raft/roles/PassiveRole.java#L548-L552

But not error or anything is returned to the leader, which means it has to timeout on the leader first and then the append is resend. This produces unnecessary delay.

**To Reproduce**

Cause a failure on append on the follower side.

**Expected behavior**

The follower sends an error back and the leader reacts appropriate with that.

**Environment:**
 - Zeebe Version: 1.3.0, 1.2.x, 1.1.x

**Comment by npepinpe** [comment]
Let's try to do it this quarter, under the assumption this isn't a difficult fix, but the main concern here is making sure that it is correct behavior - we won't get into an endless loop of the leader retrying a failed append (and potentially overwhelming the follower with requests), and that failure can be retried (or it makes sense to retry that append). The last case I specify because now, if you sent successfully some failed appends, the leader would get no response and eventually think there's a network partition. Replying now will change this behavior, and I want to make sure that's correct.
