### ISSUE TITLE
Best way to complete user tasks using zeebe client (without tasklist)

### ISSUE THREAD

**Issue by cristianbriscaru** [camunda/camunda#8953]
**Description**
I have a scenario where I have to save all the user tasks in a DB and later display them in a web app where users should be able to complete these tasks (along with user forms), what would be the best way to achieve this ?
I am exploring 2 approaches:
1) using a zeebe exporter to filter and export only user tasks to a DB, this approach seems overkill for something as basic as completing a user task job
2) having a ZeebeWorker subscribed to “io.camunda.zeebe:userTask” and saving all user tasks jobs to a DB without completing the jobs when they are initially received, this approach has issues with jobs being received multiple times when they timeout because they are not completed in the job "deadline" , also not sure how to retrieve user forms associated with the user task

What would be the best practice to complete user tasks jobs using zeebe client in this scenario (without using tasklist) ?

**Comment by stephanpelikan** [comment]
We also struggle with this!

**Our situation:**
1. We want to use Camunda Cloud, so we cannot use an custom Zeebe exporter. 
2. We need to get informed about certain usertasks: once they are created and also once they are destroyed (e.g. canceled by timer-boundary event).
3. The application shows usertasks as part of the overall UI, so we cannot use tasklist. Additionally, we would need to poll tasklist but we want to be pushed.

**Problems:**
1. Using a ZeebeWorker subscribing top “io.camunda.zeebe:userTask” passes _ALL_ usertasks of the Zeebe cluster. OK, we can do client-side filtering but this is unnecessary traffic. Zeebe-sided filtering would be more efficient but there is no possibility to restrict according to BPMN process id and element id.
2. Depending on the usertask (originated in different BPMNs) we need to retrieve a defined set of process variables. But since there is only one worker for all usertasks of the entire cluster (io.camunda.zeebe:userTask) we need to retrieve all process variables for each task. Again we need to retrieve more data than necessary.
3. We need to know about canceled task, since we use timer-boundary events and event-boundary events on usertasks. There is no possibility to get pushed when a task "dies". Actually, this problem also applies to servicetasks which do long running tasks managed by the client. If the task-lifecycle-management is done by boundary events, then there is no change to retrieve those events as part of a worker.

**Comment by kzay** [comment]
Same here, dont know how to complete user task programaticaly

**Comment by saig0** [comment]
Related forum posts:
* https://forum.camunda.io/t/complete-zeebe-user-tasks-using-the-zeebe-client/38047
* https://forum.camunda.io/t/in-camunda-platform-8-is-there-a-ready-to-use-tasklist-api-graphql-using-java-client/37602

**Comment by rj93** [comment]
Same issue here. Also would like to know how to asign a user to a userTask without using tasklist.

**Comment by rj93** [comment]
OK, I've looked into the compiled code from the `camunda/tasklist:8.1.5` docker image...

The `tasklist` service queries the Zeebe ElasticSearch indexes directly and then imports them into it's own tasklist ElasticSearch index(es). I have no idea why they have decided to do it this way and not provide public APIs on the Zeebe broker (other than to make it less welcoming to actually create your own `tasklist` replacement).

To assign a user to a `userTask` it simply sets the `asignee` / `candidateGroups` fields on the object in the `tasklist-task-1.3.0_` ElasticSearch index. If either of these has been specified in the BPMN then when it imports it will automatically set these values.

When a user wants to complete the task, it will just call the `zebeeClient`s `completeJob` public API. 

I haven't looked into how the forms are handles/values sent to the `tasklist` service.

But to recreate your own `tasklist`, you would also have to go directly to the Zeebe's ElasticSearch indexes and either import them or query/update the objects directly.

**Comment by Zelldon** [comment]
Hey @rj93 great reverse engineering :) Yes, tasklist is reading the jobs from elastic, to not activate the jobs. The assignment is happening in tasklist space and is unrelated to zeebe.

If you searching for an alternative maybe take a look at https://github.com/camunda-community-hub/zeebe-simple-tasklist or https://github.com/camunda-community-hub/zeeqs

Other than that you can simply activate jobs with `“io.camunda.zeebe:userTask` to get jobs with the related user task type. 

Hope that helps.

**Comment by megglos** [comment]
closing as officially supported and documented with https://github.com/camunda/camunda/issues/14938
